### PR TITLE
Added 2021/02/2021-02-19-take-two.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2021/02/2021-02-19-take-two.md

### CODE REVIEW

**Comment by koutsie** [comment]
Take-Two, please stop.

**Comment by kescherCode** [comment]
Well hello there, Take-Two Interactive, you're about to be turned into Give-Two Batch mode

**Comment by StraussT2** [comment]
mirror:
https://github.com/github/dmca/tree/9a7fa478578beaba947ea867c15a25e411d641d8

**Comment by sonicfan0607** [comment]
i don't believe this, this is bs; this thing doesn't looks written by professional

**Review by dic1911 — COMMENTED** [review]
Would you please just kindly and simply fuck off?
They neither provided nor used any assets of your games anyway.

**Comment by MrSorcus** [comment]
Fuck you Take-Two Interactive Software.

**Comment by jessy-lua** [comment]
facepalm

**Pull request merged**
