### PR TITLE
Fixed your notice

### PR DESCRIPTION
**Pull request by hack-everything**

### CODE REVIEW

**Review by HysMX — APPROVED** [review]
Go ahead

**Review by Rexogamer — APPROVED** [review]

**Review by Sven65 — APPROVED** [review]
LGTM!

**Comment by mininmobile** [comment]
image

**Review by mininmobile — APPROVED** [review]

**Review by lululombard — APPROVED** [review]

**Review by woina — APPROVED** [review]

**Review by aUniqueUser — APPROVED** [review]

**Comment by Nefomemes** [comment]
GitHub - Social Media for Programmers

**Review by toniz4 — APPROVED** [review]

**Review by RemiixInc — APPROVED** [review]

**Review by TheRandomMelon — APPROVED** [review]
yes.

**Review by r33int — APPROVED** [review]
LGTM

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
