### PR TITLE
Remove gender specific language

### PR DESCRIPTION
**Pull request by bee-san**
Original uses "Sir / Madam" which did not include those who do not go by neither Sir nor Madam. This language is much more inclusive & welcoming.

### CODE REVIEW

**Review by DiegoFleitas — APPROVED** [review]
Good

**Review by JakubVanek — APPROVED** [review]

**Comment by G2G2G2G** [comment]
Can't expect much from the DMCA, they're out of touch with reality

**Comment by rodjunger** [comment]
It's there for archival reasons, accepting this would be like modifying something on the internet archive

**Review by notviri — APPROVED** [review]
This, but unironically.

**Comment by animeking9901** [comment]
Unfortunately this is as the DMCA submitted it,take this up with them,not GitHub. Editing this is like editing world history,and as a they/them genderfluid i reject this pull request

**Comment by Hans5958** [comment]
Talk to their law firm, not here.

**Comment by Zeryther** [comment]
This is an archive, it's supposed to be untouched.

**Comment by l-ouis** [comment]
whyre people approving this, the point of this repo is to archive dmcas sent to github. if people change the content of letters it defeats the whole purpose. there are better ways to be progressive than editing 2 words

**Comment by Hans5958** [comment]
> 
> 
> whyre people approving this, the point of this repo is to archive dmcas sent to github. if people change the content of letters it defeats the whole purpose. there are better ways to be progressive than editing 2 words

They didn't know how the law works

**Comment by notviri** [comment]
> misunderstood the law

ah yeah that law that says you can't stream youtube videos from the official servers
that one, i forgot

**Review by JoelZimmerman — APPROVED** [review]
Good, we live in 2020. not the 1900s.

**Comment by bee-san** [comment]
This was a joke. I just thought it'd be funny that an anime profile picture schooled some big shot lawyers about basic inclusivity 😂

**Comment by Hans5958** [comment]
> ah yeah that law that says you can't stream youtube videos from the official servers
> that one, i forgot

I was not saying about this only case. I mean how the legal system as a whole works.

**Review by NeonOverflow — APPROVED** [review]

**Comment by animeking9901** [comment]
@NeonOverflow is a idiot who doesn't understand how archives and
transparency works. Modifying this file would make it no longer a original
and undermines tte transparency claim. From a genderfluid to however y'all
identify quit geing stupid

**Comment by mr-winson** [comment]
Ok. I think we can all agree whoever made this PR did it as a joke. The PRs on this repo are getting destroyed. In fact #1842 replaces all archives with the youtube-do code itself.

Thanks, please stop arguing over something stupid

**Comment by animeking9901** [comment]
fair enough lmao i am not shocked that someone did that with #1842

**Review by Mathisco-01 — APPROVED** [review]
LGTM!

**Comment by gringofe** [comment]
Dear fellow Attack Helicopter, 

...

**Review by DominykasPetke — APPROVED** [review]

**Comment by aufcedaz0234** [comment]
This is RETARDED. You're either male or female, even the computers and code you all use and write are BINARY.

**Comment by animeking9901** [comment]
Bruv what? Fuck right off with that phobic bullshit
On Oct 25, 2020 4:48 PM, "aufcedaz0234" <notifications@github.com> wrote:
>
> This is RETARDED. You're either male or female, even the computers and
code you all use and write are BINARY.

**Comment by Niquolas** [comment]
> Dear fellow Attack Helicopter, 
> 
> ...
> 
> 
> 

grow up

**Comment by NotchedDeveloper** [comment]
To be honest, we can all agree that this DMCA request was truly nothing more than a personal effort to attempt people from not being able to download songs anymore..
funny how GitHub got a DMCA request before https://ytmp3.cc did.

**Comment by Hans5958** [comment]
> 
> 
> > Dear fellow Attack Helicopter,
> > ...
> 
> grow up

no u

**Comment by jessephus** [comment]
Hi 👋🏽  We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
