### PR TITLE
Update 2020-10-23-RIAA.md to be a bit more realistic

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Made it a bit more realistic 😉

### CODE REVIEW

**Comment by 644** [comment]
DAS RITE DAS RITE DELID ALL OPEN SORES SOFTWARE IMMEDIATELY OR FACE CONSEQUENCES OF OUR BIG FAT COC (code of conduct not the other one)

**Review by stephen304 — APPROVED** [review]
LGTM :shipit:

**Review by Margen67 — APPROVED** [review]

**Review by snoozed-dev — APPROVED** [review]

**Review by nikolalukovic — APPROVED** [review]

**Review by Pan00Pernicek — APPROVED** [review]

**Review by AAGaming00 — APPROVED** [review]

**Review by imachug — APPROVED** [review]

**Review by L33Tech — APPROVED** [review]

**Comment by gormih** [comment]
No  Exhibit A in document.
Is fake document?

**Review by JordyEGNL — APPROVED** [review]

**Review by StelFux — APPROVED** [review]

**Review by mrwesleycrusher — APPROVED** [review]

**Review by juanfpo96 — APPROVED** [review]

**Review by WitherOrNot — APPROVED** [review]

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
