### PR TITLE
Fix typo in 2020-10-23-RIAA.md

### PR DESCRIPTION
**Pull request by williamd1k0**
```sh
mpv ytdl://sJgv-qBBT3Y
```

### CODE REVIEW

**Review by andraantariksa — APPROVED** [review]

**Review by mon5termatt — APPROVED** [review]

**Review by akrha — APPROVED** [review]

**Review by k1nd2020 — APPROVED** [review]

**Review by skid9000 — APPROVED** [review]

**Comment by seeyouinhell-shithub** [comment]
[Grim Reaper - See You In Hell.tar.003.tar.not.a.zip](https://github.com/github/dmca/files/5434500/Grim.Reaper.-.See.You.In.Hell.tar.003.tar.not.a.zip)
[Grim Reaper - See You In Hell.tar.002.tar.not.a.zip](https://github.com/github/dmca/files/5434502/Grim.Reaper.-.See.You.In.Hell.tar.002.tar.not.a.zip)
[Grim Reaper - See You In Hell.tar.001.tar.not.a.zip](https://github.com/github/dmca/files/5434505/Grim.Reaper.-.See.You.In.Hell.tar.001.tar.not.a.zip)
[Grim Reaper - See You In Hell.tar.004.tar.not.a.zip](https://github.com/github/dmca/files/5434509/Grim.Reaper.-.See.You.In.Hell.tar.004.tar.not.a.zip)

**Review by gluons — APPROVED** [review]

**Review by imachug — APPROVED** [review]

**Review by mininmobile — APPROVED** [review]
image

**Review by analotia — APPROVED** [review]

**Review by Nefomemes — APPROVED** [review]
GitHub - Social Media for Programmers

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by MrMelon54** [comment]
Github should release a full report about this DMCA takedown and should explain everything in detail and have a thread where people can ask question (should they have any). Also youtube-dl pretty much does the same as what youtube in the browser does and thus the RIAA should takedown youtube.com as well.

**Pull request closed without merging**
