### PR TITLE
Delete this claim with 0 proof LMAO

### PR DESCRIPTION
**Pull request by BBDDAlex**
Completely baseless claim because the leak of the unc0ver source code was coincidentally close to before the release of odyssey, please never make a DMCA claim again

### CODE REVIEW

**Comment by rodent5** [comment]
+1

**Comment by charge1337** [comment]
+ 1

**Comment by brennanleblanc0** [comment]
+1 Many of the tools used in the repository in question (Chimera13) used open source tools/code, as well as repository owner's own tools/code.

**Comment by ncorbuk** [comment]
+1

**Comment by iomintz** [comment]
Pull requests to this repository are unmonitored. If you'd like to counter a DMCA claim against *your code*, contact GitHub.

**Comment by relative** [comment]
lol

**Comment by luxxxxy** [comment]
@relative fuck off, fncxpro, aka relative, aka "I threatened to swat someone on a minecraft server"

**Comment by resynth1943** [comment]
Lmao

**Review by VoltrexMaster — APPROVED** [review]

**Comment by jessephus** [comment]
As pointed out [above](https://github.com/github/dmca/pull/7417#issuecomment-655264432), we do not regularly monitor this repository, and we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to it. 

If you are still interested in contacting GitHub, see our [Contributing Guidelines](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to see what your alternatives are.

**Comment by resynth1943** [comment]
@jessephus so sad you gonna cry?

**Pull request closed without merging**
