### PR TITLE
Why should the email address be private?

### PR DESCRIPTION
**Pull request by MrMelon54**
Where is the email address?

### CODE REVIEW

**Comment by mutageneral** [comment]
I presume that if you search around on the internet you must be able to find some emails addresses that belong to the RIAA

**Comment by mutageneral** [comment]
According to [this Google answers tread from 2004](http://answers.google.com/answers/threadview?id=424032) their public non employee specific email about piracy is **antipiracy@riaa.com**  

You can also make a [hunter.io](https://hunter.io/) account and put "riaa.com" in it. I won't post the result of that here because I don't want my GitHub nuked, it has the name and phone number of specific people. If you do so, I would recommend you look up who are the CEOs and contact them, not random lower grade employees because that would kinda be a dick move.

**Comment by My1** [comment]
maybe because the spricifc employee is not something that should be overly public

**Comment by mutageneral** [comment]
> maybe because the spricifc employee is not something that should be overly public

Its public though, hunter find them by scanning articles on the riaa.com website. At the bottom of some of them blog like article on their site some employees put their email and name there.

**Comment by My1** [comment]
But it should maybe not be public which employee filed this, i mean we all know gow unforgiving the internet can be. And showing the address especially if it is publicly known even more as you can connect thw dots even easier.

The individual employee should not suffer from the decisions of the place they work for.

**Comment by MrMelon54** [comment]
> The individual employee should not suffer from the decisions of the place they work for.

Yeah I guess thats fair

**Comment by My1** [comment]
Kinda lol tho that i of all people who is usually right upfront burning companies for dumb bs, play the voice of reason here lol.

**Comment by MrMelon54** [comment]
I want someone to blame for youtube-dl not being on Github and I don't know if that should be this specific employee, the DIAA in general or Github (for not standing up for the project and helping it). It's not the project owner's fault that the DIAA thinks it is used just to download "their" content just because thats how a select few people use it.

**Comment by My1** [comment]
well it should obviously be the RIAA (with an R). that github axes this for now is sadly the state of the law that they kinda have to takedown first and argue later to stay in the safe harbor of not being sued directly. and also while the argument the RIAA is using is absolutely bonkers especially since that whatever cipher thingis as far as I heard from a friend not really any cipher aka encryption (beyond TLS for that matter) but more like a hotlink protection for the raw video files. similar to how when you request a windows ISO download from a non-windows machine you get a URL that's not valid in a limited scope of time, IP or whatever and basically is likely there to as said prevent hotlinking that stuff, the argument they have while plotting all things along including the court ruling from German Landgericht hamburg (absolutely infamous for being super pro copyright owners, and gettig decisions axed on the next instance on the regular), it all is standing currently. it's a house of cards but for now it stands and would need to be challenged.

although maybe getting the Streisand Experience on Full blast helps the RIAA to see that what they tried was dumb

**Comment by MrMelon54** [comment]
And the fact that the Github DMCA repo has copies of the code in the tree pushed due to a bug Github doesn't want to fix (so technically that means the DMCA repo needs to me taken down too for having a copy of the offending code?)

**Comment by My1** [comment]
I dunno how this all works internally, but this kinda more looks like an implicit linking fail or whatever rather than that the offending commits being actually part of the repo

**Comment by MrMelon54** [comment]
Yeah but technically the only way to access them is to go to a url which is a sub folder or the dmca repo and description and contributors match the ones for this repo so I would say that it is within this repo

**Comment by Project-Magenta** [comment]
The code is in a pull request, no bug here

**Comment by MrMelon54** [comment]
> The code is in a pull request, no bug here

The whole source code was available here: https://github.com/github/dmca/tree/416da5 the other day but it appears to have been removed (someone at Github obviously didn't like it). The only way to get it there was by abusing a bug within Github.

**Comment by Project-Magenta** [comment]
Yeah, that's how pull requests work. They store code in a hidden branch of the target repository.

**Comment by MrMelon54** [comment]
Oh ok but I didn't see a pull request for this hidden branch so it confused me a little. (I might have just not seen the PR?)

**Comment by Project-Magenta** [comment]
It was called 😳

**Comment by MrMelon54** [comment]
Oh lol I must have missed that one

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

As to the specific question raised...

>please allows us to see the email for all youtube-dl lovers to spam until the youtube-dl repo is returned back onto github

You make a compelling argument... to keep the email address private. 😆 

Seriously, though, GitHub redacts personal information such as email addresses from the notices we publish, as explained in our [DMCA Policy](https://docs.github.com/en/github/site-policy/dmca-takedown-policy#d-transparency):

>We post redacted copies of any legal notices we receive (including original notices, counter notices or retractions) at https://github.com/github/dmca. We will not publicly publish your personal contact information; we will remove personal information (except for usernames in URLs) before publishing notices.

We understand that you may have other questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by MrMelon54** [comment]
> You make a compelling argument... to keep the email address private. 😆

Oh yeah. I wonder if the employee feels bad about taking down youtube-dl as they were forced to by their boss or if they chose to submit a takedown request after finding the repo?

Also why would they only submit a request for youtube-dl... what about all the other clients used for downloading youtube videos?

**Comment by mutageneral** [comment]
> But it should maybe not be public which employee filed this, i mean we all know gow unforgiving the internet can be. And showing the address especially if it is publicly known even more as you can connect thw dots even easier.
> 
> The individual employee should not suffer from the decisions of the place they work for.

Exactly why I asked not to contact random employees and instead contact the anti-piracy email or the CEO's emails.

**Comment by MrMelon54** [comment]
> > But it should maybe not be public which employee filed this, i mean we all know gow unforgiving the internet can be. And showing the address especially if it is publicly known even more as you can connect thw dots even easier.
> > The individual employee should not suffer from the decisions of the place they work for.
> 
> Exactly why I asked not to contact random employees and instead contact the anti-piracy email or the CEO's emails.

Yeah I totally understand that

**Pull request closed without merging**
