### PR TITLE
Update 2018-02-09-Apple.md

### PR DESCRIPTION
**Pull request by rodrigopvai**
I already removed and sent an email to Github support

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
The files in the repository are just for informational purposes and once added, can't be edited.

**Comment by marco-a** [comment]
Quoting the README (emphasis mine):

> **We do not accept Pull Requests in this repository.** Feel free to comment or make suggestions, but note that we do not actively monitor contributions to this repository. If you would like to contact GitHub about this repository, please contact GitHub Support. If you would like to submit a DMCA notice or counter notice, see our DMCA Policy pages for information on how to do so.

**Comment by IRobL** [comment]
I believe my repo was flagged by an automated system and no actual person ever looked at my repository and found that it was objectionable.  I'm considered by Github's handling of takedown notices.  I glanced through other people's repos and found that @jeffroeq published a notes repository in good faith and although I can no longer read the contents, I presume it did not consist of any copyright violations either.  

Where can we file issues to resolve this?

**Comment by jeffroeq** [comment]
Like @IRobL, I believe my repo was flagged by an automated system. My repo was just my own collection of notes I have compiled over my 10+ years of performing Linux/UNIX admin work and only contained notes or scripts to perform admin tasks. There are notes on how to perform tasks such as forcing fail-overs of Veritas clusters, growing Linux volumes, how to Ansible, etc...

**Comment by jessephus** [comment]
@rodrigopvai, @IRobL & @jeffroeq - As noted above, this repository is really only for informational purposes. If you have concerns about GitHub's processing of DMCA notices and/or questions about your particular cases, please [contact GitHub Support](https://github.com/contact) with your questions and concerns. Thanks.

**Comment by IRobL** [comment]
@jessephus, thank you.  I reached out over email but have not heard back.  I didn't even get an automated "you're in a queue to be served" response.  Are you on the support team?  I would like this sorted out so perhaps you could share your direct email with me?  

I also contacted a chat room at my company to see if anyone there knew who was responsible, but they said their chat room doesn't have anything to do with DMCA take downs.  This is a very confusing, if not rude way to inform an employee that they may have made copyrighted material available on public github, don't you think?  

I filled in the email form and pointed them to this PR, In the meantime I just want to view the commit sha that was on the public github's master branch so I know what notes were online originally to get to the bottom of what was and wasn't shared and understand whether I have any other personal repos at risk by tracking them into my works computer systems.

**Pull request closed without merging**
