### PR TITLE
Corrupt 2020-10-23-RIAA.md

### PR DESCRIPTION
**Pull request by mscalindt**
some things shouldn't exist

### CODE REVIEW

**Comment by Uniminin** [comment]
***100%*** Agree!

**Review by Uniminin — APPROVED** [review]
Great Job!!!

**Review by LiveEmily — APPROVED** [review]

**Review by Firepal — APPROVED** [review]
Nice and corrupted. Just how it should be. Merge it pronto!

**Review by rzk3 — APPROVED** [review]
A much needed fix! Merge ASAP.

**Review by shirt-dev — APPROVED** [review]

**Review by shahzebgit — APPROVED** [review]

**Review by DumbGameMaker — COMMENTED** [review]
looks good, but didnt someone already make the letter actually true? "The RIAA is a bunch of idiots who do what we want because we are babies" or something

**Comment by DumbGameMaker** [comment]
ehh wth i approbe

**Review by DumbGameMaker — APPROVED** [review]

**Review by koutsie — APPROVED** [review]
Yeah, LGTM.

**Comment by Firepal** [comment]
> looks good, but didnt someone already make the letter actually true? "The RIAA is a bunch of idiots who do what we want because we are babies" or something

you were too late

**Comment by will-pace** [comment]
Hi 👋 We are closing this pull request because we do not accept contributions to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with GitHub’s Community Guidelines.

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by qogusdn1017** [comment]
:/

**Pull request closed without merging**
