### PR TITLE
Delete spurious DMCA request.

### PR DESCRIPTION
**Pull request by darrenmartyn**
Delete spurious DMCA request made by the RIAA, revert changes.

### CODE REVIEW

**Comment by iomintz** [comment]
This joke isn't funny anymore, and wastes time for github staff and those of us who watch this repository.

**Comment by Kurtoid** [comment]
Agreed, we've bothered them enough.

**Comment by catSIXe** [comment]
We need more people spamming this repository and break GitHub. GitHub is a Microshat Product and therefore, it is by definition SHIT. Just like Microshat, shats on Minecraft Players with the Microshat Account Enforcement... People will leave.

**Comment by sturdevant** [comment]
I completely agree with the suggestion that people should be writing to their representatives in government about changing copyright law, and I wanted to give a few helpful tips to anyone who has never written to their member of Congress before.

The first thing I'd recommend is to start with a template. This will save you some effort since the most effective letters to Congress generally all follow the same format. If you're not sure of where to find templates, you can look at [a few excellent examples here](https://www.dreamstime.com/photos-images/blank-check.html). Once you've selected a template, it's time to fill it in with some details! In the "To" section, you'll want to fill it in with your representatives name, and you'll also want to put the current date in the appropriate field as well.

In the section labelled "amount", this is where you'll want to make your most compelling argument about the need to pass the law that you're advocating for. It will be up to you to decide what to write for that part specifically, but as a general rule, the larger the number, the more persuasive your argument will be, and therefore the more likely it is that your elected official will listen to what you have to say. Don't forget to sign your name at the bottom so that your representative knows that it came from one of their constituents.

Lastly, I'd like to point out that GitHub strongly encourages anyone who disagrees with the DMCA ~shake down~ take down process to write to their members of Congress to voice their opinions. GitHub's parent company, Microsoft, [has a lot of experience writing to Congress about passing legislation](https://www.opensecrets.org/industries/indus.php?Ind=B), so they definitely know what they're talking about!

**Comment by will-pace** [comment]
Hi 👋 We are closing this pull request because we do not accept contributions to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with GitHub’s Community Guidelines.

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by thetayloredman** [comment]
@will-pace If you are allowing discussions, then why not allow issues or make one central PR for discussion?

**Comment by catSIXe** [comment]
> @will-pace If you are allowing discussions, then why not allow issues or make one central PR for discussion?

Thats what we call Censorship... Shathub aka Microshat has Experience with this...

**Pull request closed without merging**
