### PR TITLE
Added 2017/2017-06-15-CCP.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2017/2017-06-15-CCP.md

### CODE REVIEW

**Comment by vitalkanev** [comment]
Not pulled?
I guess something bad happened...

**Comment by WilliamFeely** [comment]
And a couple weeks later the piracy scene has picked it up.

**Comment by NazarFogmann** [comment]
In Russia, DMSA has no legal force. A redict has every right to do what he does. Because it does not violate the laws of the Russian Federation.

**Comment by WilliamFeely** [comment]
You're wrong.  The DMCA protects GitHub from lawsuits.  Same if the owner of that anime you copied for your profile takes offense.

**Comment by actsl** [comment]
It is my repository that was disabled, and that is still disabled.

I submitted a counter-notice in a few days after the takedown notice, why is my counter-notice not submitted to this repository? Anderson from GitHub emailed me and said that GitHub proceeds from my counter-notice, and after 10 working days my repository will be restored, if there is no legal action against me, etc, etc. I have not heard from anyone since then. 10 working days have passed, and my repository is still disabled.

I'm not from the Russian Federation if you like to know, i'm from an EU member state, and legal action can be taken against me.

To state it again, all content of my repository committed by git was written by me or had an open source license, the same as my repository https://github.com/actsl/kiss_sdl2 that i uploaded after the takedown, that is almost identical, except that i were not allowed the access to my old repository to make an exact copy, and i cannot make sure that the last commit and such is there. So that the users will suffer less from the takedown. GitHub decided not to disable this new repository. My repository was popular, had 64 stars, and it took from me a year of hard work to develop. The biggest problem caused by that takedown is that most users accessed my repository from the sites that have been made read-only, such as the old SDL forum and other links that i couldn't change. So i cannot now upload my repository again to the same URL.

As i said, all the content of my repository was written by me, or were open source (like the font file), i even didn't accept any pull requests to make sure that there is no content of unknown origin. The only file that contained any material of unknown origin or copyright, was the file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip that was a file uploaded as an attachment to an issue, by the sole request by the person who submitted the DMCA notice, to help that person to build some code for Android. That zip archive contained some files that had no copyright notice, the real origin or copyright of which i were not aware of, and which is not known to me even today. This was the only content in my repository whatsoever, that contained anything without a clear open source copyright, the claimant also mentioned that file in ones takedown notice. I were willing and really wanted to delete that file, completely contradictory to what the author of the takedown notice claimed, but GitHub confirmed me that i cannot by myself remove files uploaded as attachments to issues, and GitHub did not delete that file, in spite that i repeatedly requested GitHub to delete that file. So there was no way how i could prevent the takedown of my repository. If ever the repository will be restored, i ask GitHub again to delete that file, in hope that it will be finally deleted then.

And now it seems the issue remains this. My counter-notice is evidently nowhere publicly posted, in spite that GitHub claims that they proceed from it. And i doubt whether my counter-notice was ever shown to the person who submitted the takedown notice. The issue thus like remains unresolved forever, like because of no response from me, that is not true. And thus not only can my repository ever restored, but also nothing else can be done, like the repository cannot be deleted and the URL made available to me so that i can upload the repository again to that same URL.

Nothing can be done, everything remains unresolved forever, and the damage is done forever, for the only reason that there is no response from me. Which is not true.

I only helped a person by that person's request to build some code for Android for that person, the code which that person referred to somewhere in the Internet and that had unknown origin and no copyright notices. I wanted to delete that file, GitHub confirmed i cannot, and GitHub didn't delete that file. GitHub did not ever contact me before disabling my entire repository. That is all this issue can ever be about, i have never knowingly uploaded any files with no open source copyright, not to talk that i wanted to steal any copyrighted files from anyone, i even did not accept any pull requests to make sure that all content in my repository is only written by me.

My repository was disabled because of misidentification, my counter-notice was evidently ignored in spite of letting me know the contrary by the email written to me. All issue remains unresolved, because seemingly anything written by me is completely ignored.

**Comment by actsl** [comment]
PS I know nothing about the computer game EVE Online, have no idea whether any part of the code of that game were in the file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip and that is anywhere in my repository. Referred to in this pull request by the person who also submitted the takedown notice of my repository. The claimant claimed that all allegedly copyrighted code was written by themselves, no it looks that instead it is instead about some code allegedly copyrighted by EVE Online.

No such code is in my repository, why that person asked me to hep them and upload any of the code written by EVE Online, i don't know. Please GitHub finally delete the nonsense file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip because i don't know what next claims there may be about what else copyrighted material by whoever it allegedly contains. I never wanted that file to be in my repository, that person wanted me some of the code that person referred to, to buld for Android, i were willing to help that person, but that person probably did not act in good faith in now accusing me in trying to steal some code copyrighted by some weird companies that i have never heard of and never knew anything about their code.

GitHub please end this doubtful activity and please finally delete the nonsense file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip . Thank you.

**Comment by WilliamFeely** [comment]
I think you need to contact GitHub directly regarding that issue.
P.S.  You can't escape liability by being in a country like Russia; you are liable no matter where in the world you are if you victimize a citizen of the US or EU.

**Comment by actsl** [comment]
> I think you need to contact GitHub directly regarding that issue.

I said, i contacted GitHub directly, you didn't read what i wrote.

> P.S.  You can't escape liability by being in a country like Russia; you are liable no matter where in the world you are if you victimize a citizen of the US or EU.

I am a citizen of EU, and i said legal action can be taken against me. Again you didn't read what i wrote.

I did not hear from anyone though, not from GitHub, not from anyone who wants to take any legal action against me.

Also i can take legal action against a citizen of US or EU, who makes conflicting claims of any copyright belonging to them, then instead to some little known company EVA Online, etc.

GitHub does not delete the file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip about which all these questionable claims were made. It were good for GitHub to finally delete the file https://github.com/actsl/kiss_sdl/files/1030147/project1.zip , such questionable claims against my, and now it looks like also against other repositories, are not good for GitHub, and all must be done to end them. I were always willing to co-operated, but GitHub never contacted me before they disabled my repository, now it looks like that they even don't agree to delete my entire repository, so i can use that URL again, if they refuse or cannot never un-disable my repository. To make certain that none of such questionable files are anywhere, and once and for all end all questionable claims.

**Comment by actsl** [comment]
I submitted my counter notice against this takedown notice today again to copyright@github.com . I hope that this time it will be submitted to this repository different from my previous counter notice that is not in this repository. My counter notice that i sent today, was as follows.


I have read and understand GitHub's Guide to Filing a DMCA Counter Notice.
 
The disabled content was my entire repository https://github.com/actsl/kiss_sdl .
 
<private, my physical address, email address, telephone>
 
I swear, under penalty of perjury, that I have a good-faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled.
 
I consent to the jurisdiction of Federal District Court for the judicial district in which my address is located (if in the United States, otherwise the Northern District of California where GitHub is located), and I will accept service of process from the person who provided the DMCA notification or an agent of such person.

<private>

**Comment by actsl** [comment]
Sorry, this pull request was not about my repository, i found it on the DMCA takedown notice against my repository, so mistakenly thought it is about that takedown notice.

I created a new pull request for my counter notice, any further comments please write there.

**Comment by jessephus** [comment]
This notice was merged in https://github.com/github/dmca/pull/1803/files?diff=unified#diff-c3242ea0ca8ced6e5751880a8cc781db

Strange that this one was left open. Bad Hubot!

**Pull request closed without merging**
