### PR TITLE
no

### PR DESCRIPTION
**Pull request by SuperLeaf1995**
no

### CODE REVIEW

**Comment by AtieP** [comment]
lmao

**Review by notpushkin — APPROVED** [review]

**Review by VisualDevelopment — APPROVED** [review]

**Review by NotchedDeveloper — APPROVED** [review]

**Review by ZeProf2Code — APPROVED** [review]

**Review by zero-systems — APPROVED** [review]

**Review by bencark — APPROVED** [review]
nice

**Review by mrwesleycrusher — APPROVED** [review]

**Review by mrwesleycrusher — APPROVED** [review]

**Review by Nefomemes — APPROVED** [review]

**Review by connernilsen — APPROVED** [review]
I'm deceased

**Comment by 0xqoob** [comment]
I agree, thank you for your contributions

**Review by 0xqoob — APPROVED** [review]

**Comment by soumitradev** [comment]
how

**Review by soumitradev — APPROVED** [review]
how

**Comment by MightyPork** [comment]
ban browsers :zap:

**Review by alexmercerind — APPROVED** [review]

**Comment by aurelian2** [comment]
Yes

**Review by sleepy-monax — APPROVED** [review]
yes.

**Review by branc116 — APPROVED** [review]

**Review by TheRealGLH — APPROVED** [review]

**Review by cristianmarint — APPROVED** [review]

**Review by TheRandomMelon — APPROVED** [review]
I mean it's true

**Review by pmaasz — APPROVED** [review]
I approve.

**Review by Lubieerror — APPROVED** [review]

**Comment by thehalleffect** [comment]
Yes.

**Review by MrAlexEsisteGia — APPROVED** [review]

**Review by mblumtritt — APPROVED** [review]

**Review by Sven65 — APPROVED** [review]
Yes.

**Review by skyventuree — APPROVED** [review]
approved

**Review by emilweth — APPROVED** [review]

**Review by MrMelon54 — APPROVED** [review]

**Review by Mathisco-01 — APPROVED** [review]

**Review by AAGaming00 — APPROVED** [review]
yes

**Review by robingall2910 — APPROVED** [review]
yup

**Review by starikcetin — APPROVED** [review]
Best refactor I have seen in my entire career.

**Review by aurelian2 — APPROVED** [review]
I mean it's right

**Review by myrvogna — APPROVED** [review]
yes

**Review by ThatGeekyWeeb — APPROVED** [review]

**Review by mushchlo — APPROVED** [review]
Yeah, good, OK.

**Review by kallydev — APPROVED** [review]

**Comment by ThatGeekyWeeb** [comment]
youtbe-dl's purpose is not to get around copyright, but to access youtube videos without a browser. And really youtube it's self loads the video into my frame-buffer, I could simply grab it from there. And there are thousands of websites that do just this.

**Review by ehyuman — APPROVED** [review]

**Review by d0p1s4m4 — APPROVED** [review]

**Review by Keyboard-Slayer — APPROVED** [review]

**Review by busybox11 — APPROVED** [review]

**Review by Freeloo — APPROVED** [review]

**Review by GizmoOAO — APPROVED** [review]

**Review by sxzz — APPROVED** [review]

**Review by pragmaticpandy — APPROVED** [review]

**Review by HitSyr — APPROVED** [review]

**Review by AEverstone — APPROVED** [review]

**Review by Technach — APPROVED** [review]

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the excellent discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by 0xqoob** [comment]
No

**Comment by mushchlo** [comment]
No

**Comment by bencark** [comment]
No

**Comment by ThatGeekyWeeb** [comment]
This some major bull, RIAA is just a company with a crap ton of money and the power to do anything because of it, there is 0 proof the purpose of yt-dl is to avoid copyright, an example in plain text proves nothing at all...

**Comment by AAGaming00** [comment]
no

**Comment by skyventuree** [comment]
no
just no

**Comment by VisualDevelopment** [comment]
no

**Comment by Sven65** [comment]
Booo!

**Comment by aurelian2** [comment]
no

**Comment by mental32** [comment]
image

**Review by coolshaurya — COMMENTED** [review]
Excellent change

**Comment by 0xqoob** [comment]
> Excellent change

begone

**Comment by coolshaurya** [comment]
> 
> 
> > Excellent change
> 
> begone

ok, but where do i go?

**Pull request closed without merging**
