### PR TITLE
suck my dick.

### PR DESCRIPTION
**Pull request by amirothman**
dumb fucks doing fucking dumb shit needs to stop

### CODE REVIEW

**Comment by gsckoco** [comment]
lol what are you actually braindead?

**Review by xfnw — CHANGES_REQUESTED** [review]
why not just delete the file?

**Comment by stephen304** [comment]
୧༼ಠ益ಠ༽୨ NOW WE RIOT ୧༼ಠ益ಠ༽୨

**Review by polarisfm — APPROVED** [review]
strong dom energy

**Comment by notviri** [comment]
😳

**Review by Margen67 — APPROVED** [review]

**Comment by gusbemacbe** [comment]
RIAA needs to be strongly boycotted worlwide.

**Comment by faissaloo** [comment]
Just found a picture of OP
image

**Comment by Vixtron** [comment]
> Just found a picture of OP
> image

Welcome to based department

**Review by Vixtron — APPROVED** [review]

**Review by cristianmarint — APPROVED** [review]

**Review by alenpaul2001 — APPROVED** [review]

**Comment by mininmobile** [comment]
image

**Review by mininmobile — APPROVED** [review]

**Review by JordyEGNL — APPROVED** [review]

**Review by KnockKnockP — APPROVED** [review]

**Review by analotia — APPROVED** [review]

**Comment by n0rmancodes** [comment]
> lol what are you actually braindead?

if not wanting a legal program that even fucking google uses in their own projects in braindead, count me in

**Review by digmorepaka — APPROVED** [review]

**Comment by faissaloo** [comment]
> if not wanting a legal program that even fucking google uses in their own projects is braindead, count me in

Wait what do they use it for?

**Comment by n0rmancodes** [comment]
> Wait what do they use it for?
i dont remember what they used it for, exactly. as a result, i could be remembering it wrong and deleted my comment.

**Review by Nefomemes — APPROVED** [review]

**Review by kubapolish — APPROVED** [review]

**Comment by jessephus** [comment]
Hi. We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Since this thread is inconsistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines), we are locking this thread from any further comments.

**Pull request closed without merging**
