### PR TITLE
Added 2015-09-23-VibeMedia

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2015-09-23-VibeMedia

### CODE REVIEW

**Comment by jomo** [comment]
Have you decided to no longer use markdown or is this a mistake?

(Not sure whom to mention for this. @ScarlettSparks or @jessephus perhaps? :)

**Comment by jomo** [comment]
Either way, [the link](https://github.com/github/dmca/blob/master/2015-09-23-VibeMedia.md) on the [repo](https://github.com/vladkrasovsky/site1) is broken.

**Comment by jessephus** [comment]
hah... i was just fixing that:
https://github.com/github/dmca/commit/99647c6cb5182c60cee1b30e630de590dc276168

**Comment by jomo** [comment]
:+1:

**Pull request merged**
