### PR TITLE
Move files into folders to ease reading

### PR DESCRIPTION
**Pull request by jeroenvisser101**
*NOTE: I've seen this project doesn't accept PRs, but I do see this as a suggestion towards GitHub for making this repository more useful.*

Files were being truncated as the list became longer than 1000 files,
which made reading files a real pain. This should account that, and make
browsing them a lot easier.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
(this would probably change some of your workflow using hubot, so you might want to consider only moving files that are not in the current year, so the hubot workflow wouldn't change?)

**Comment by jessephus** [comment]
hi @jeroenvisser101 - Thanks for the note. We are aware of this issue. Just refoldering alone will break the links on any currently disabled projects. So we're trying to figure out internally how to fix the one problem without creating another.

**Comment by jomo** [comment]
Just some ideas:

0. Create new repo (/legal/dmca, /dmca/xyz, /github/chillingeffects , ...)
  - The old repo would stay here as it is
  - The new repo would contain old and new letters nicely structured
0. Symlink the current files
  - Would still be a long list of files, but at least it would stop growing
  - All files (apart from the links) would be nicely structured

**Comment by jeroenvisser101** [comment]
@jessephus – thanks for replying so quickly! I understand the issue at hand. I might have some suggestions for solving it as well:

1. Create a new branch, not called `master` (e.g. `restructured`), and make it default. If I'm correct, all urls refer to `.../blob/master/...`, so those will still refer to the old files, whereas people visiting this repo again will see the new branch and get new urls.
2. Possibly the same system that redirects users when a repository/org is renamed, can be used for redirecting these files, but that might have some side-effects. Apart from that, this might be fairly fault-tolerant since it would require manually inserting these into the database, which seems tricky to me.

**Pull request closed without merging**
