### PR TITLE
Update 2018-11-08-Manning.md

### PR DESCRIPTION
**Pull request by hustbill**
I removed this book from the repo. Thanks.
remove "https://github.com/hustbill/tech-books/blob/cf19ec221ba27b9755beee3bd8047b79c322207b/Akka/Akka_in_Action.pdf"

### CODE REVIEW

**Comment by syzutopia** [comment]
Remove this

https://github.com/github/dmca/pulls

**Comment by bonexd** [comment]
why are you trying to remove yourself from the dmca? aww is it making you look bad?

**Comment by iomintz** [comment]
Pull requests are unmonitored. Email GitHub for DMCA issues.

**Comment by jessephus** [comment]
Yeah... ☝🏽 this. We do not regularly monitor this repository, and we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to it. 

If you are still interested in contacting GitHub, see our [Contributing Guidelines](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to see what your alternatives are.

**Pull request closed without merging**
