### PR TITLE
no

### PR DESCRIPTION
**Pull request by JaxTheWolf**
no

### CODE REVIEW

**Review by johanneslosch — CHANGES_REQUESTED** [review]
Please don't change everything and replace it with "no".

**Comment by ivanka2012** [comment]
no

**Comment by ralsei** [comment]
no

**Review by oatmealine — APPROVED** [review]

**Review by polarisfm — APPROVED** [review]
no

**Comment by Gangster8192** [comment]
no

**Comment by Sven65** [comment]
no

**Comment by oatmealine** [comment]
no

**Comment by Bandie** [comment]
no

**Comment by Awesomerly** [comment]
no

**Review by Bandie — APPROVED** [review]
no

**Review by drewcassidy — APPROVED** [review]

**Comment by drewcassidy** [comment]
no

**Review by amirothman — APPROVED** [review]
no

**Review by lithomas1 — APPROVED** [review]
no

**Review by Genvara — APPROVED** [review]
no

**Comment by adi8900** [comment]
no

**Comment by hawkshoe** [comment]
no

**Comment by bladefox1337** [comment]
yesn't

**Review by Margen67 — APPROVED** [review]
no

**Review by bladefox1337 — APPROVED** [review]
yesn't

**Comment by keesvv** [comment]
no

**Review by RektWithStyle — APPROVED** [review]
no'nt'nt

**Comment by pikami** [comment]
no

**Review by DannyJJK — APPROVED** [review]

**Review by pikami — APPROVED** [review]

**Review by BlueRaccoonTech — APPROVED** [review]
no

**Comment by CreepySkeleton** [comment]
YES.

**Comment by Bandie** [comment]
no

**Comment by Genvara** [comment]
no

**Comment by PhoenixLandPirate** [comment]
Yesn't

**Comment by bgette** [comment]
YESN'T

**Review by kanna5 — APPROVED** [review]

**Comment by Justasic** [comment]
No.

**Comment by curlpipe** [comment]
No

**Comment by EnderDev** [comment]
no

**Review by dxf — APPROVED** [review]

**Review by Draem — APPROVED** [review]
no

**Comment by huaji233333** [comment]
no

**Review by huaji233333 — APPROVED** [review]
no.

**Review by l1ving — APPROVED** [review]

**Comment by shirt-dev** [comment]
no

**Review by shirt-dev — APPROVED** [review]

**Review by williamd1k0 — APPROVED** [review]

**Comment by williamd1k0** [comment]
no

**Review by andraantariksa — APPROVED** [review]
no

**Review by sodle — APPROVED** [review]

**Comment by sodle** [comment]
big nope

**Review by CheezusChrust — APPROVED** [review]
no.

**Review by mon5termatt — APPROVED** [review]
no

**Comment by mrkev** [comment]
no

**Review by mrkev — APPROVED** [review]

**Review by brrianalexis — APPROVED** [review]

**Comment by fdschonborn** [comment]
no

**Comment by balthild** [comment]
no

**Review by Fusl — APPROVED** [review]
no

**Review by an0nym0u55 — APPROVED** [review]

**Review by subodhk01 — APPROVED** [review]

**Comment by subodhk01** [comment]
no

**Comment by calvinthefreak** [comment]
no!

**Review by gluons — APPROVED** [review]

**Comment by gluons** [comment]
no

**Review by ftruzzi — APPROVED** [review]

**Review by code-rgb — APPROVED** [review]

**Comment by code-rgb** [comment]
no

**Review by exception — APPROVED** [review]

**Comment by AlexFlipnote** [comment]
no

**Review by geopic — APPROVED** [review]

**Review by llGOKUll — APPROVED** [review]

**Review by AAGaming00 — APPROVED** [review]
no

**Review by tth05 — APPROVED** [review]
no

**Review by RAnders00 — APPROVED** [review]

**Comment by bagyoni** [comment]
no

**Comment by recapitalverb** [comment]
- [ ] no

**Review by recapitalverb — APPROVED** [review]
no

**Review by imachug — APPROVED** [review]

**Comment by krivokuca** [comment]
no

**Comment by auxiliary-character** [comment]
image

**Review by josiahmokob0 — APPROVED** [review]

**Review by L33Tech — APPROVED** [review]

**Comment by jacksonisiah** [comment]
no

**Comment by livingsilver94** [comment]
no

**Review by livingsilver94 — APPROVED** [review]

**Review by dgw — APPROVED** [review]
no

**Comment by Conight** [comment]
fxxk no

**Comment by Merith-TK** [comment]
no

**Comment by Poopooracoocoo** [comment]
no ⓪w⓪

**Review by AlexFlipnote — APPROVED** [review]

**Review by Poopooracoocoo — APPROVED** [review]

**Comment by toby3d** [comment]
yesn't

**Review by analotia — APPROVED** [review]

**Comment by SecondRateDeveloper** [comment]
nah

**Review by Ag3ntSky — APPROVED** [review]
no indeed

**Comment by CIosure** [comment]
no

**Review by CIosure — APPROVED** [review]

**Comment by waaberi** [comment]
no

**Review by waaberi — APPROVED** [review]

**Comment by AndreiJirohHaliliDev2006** [comment]
I hate the memes. This should be *case closed* if I request for changes.

**Review by AndreiJirohHaliliDev2006 — CHANGES_REQUESTED** [review]
gud no

**Review by merothh — APPROVED** [review]
LGTM

**Comment by HafitzSetya** [comment]
No

**Review by TipzTeam — APPROVED** [review]
gud commit

No

**Comment by pratyakshm** [comment]
no

**Review by Rasenkai — APPROVED** [review]

**Comment by Rasenkai** [comment]
no

**Review by TipzTeam — APPROVED** [review]
no

**Comment by TipzTeam** [comment]
> I hate the memes. This should be _case closed_ if I request for changes.

I hate you. Ok no we are friends.

**Comment by dxf** [comment]
ppl can we stop sending me emails titled "no" thanks

**Comment by Rasenkai** [comment]
> ppl can we stop sending me emails titled "no" thanks

Unsub thread wen?

**Comment by Bandie** [comment]
unsubscribe? no

**Comment by TipzTeam** [comment]
> ppl can we stop sending me emails titled "no" thanks

no

**Comment by dxf** [comment]
no

**Review by 06kellyjac — APPROVED** [review]

**Comment by JaxTheWolf** [comment]
> unsubscribe? no

Hotel? Tri-va-- no.

**Review by Techwolf12 — APPROVED** [review]

**Comment by r3b311i0n** [comment]
no

**Comment by Scupake** [comment]
no

**Comment by tth05** [comment]
Ye- no.

**Comment by Asclor** [comment]
"No"

**Review by danglduy — APPROVED** [review]

**Review by r3b311i0n — APPROVED** [review]

**Comment by TCLNA** [comment]
no

**Comment by pokurt** [comment]
nein

**Comment by jonatan1609** [comment]
no

**Review by tth05 — APPROVED** [review]

**Review by tth05 — APPROVED** [review]

**Review by tth05 — APPROVED** [review]

**Review by Bandie — APPROVED** [review]

**Review by Bandie — APPROVED** [review]

**Comment by elgabo86** [comment]
non

**Comment by AndreiJirohHaliliDev2006** [comment]
> > ppl can we stop sending me emails titled "no" thanks
> 
> Unsub thread wen?

When this was case closed.

**Review by alexmercerind — APPROVED** [review]
no

**Review by vladislav805 — APPROVED** [review]
no

**Review by RunAge — APPROVED** [review]

**Comment by thehalleffect** [comment]
no

**Review by spdfnet — APPROVED** [review]

**Comment by caioalonso** [comment]
no

**Review by Justasic — APPROVED** [review]

**Comment by jessephus** [comment]
no

**Comment by Bandie** [comment]
@jessephus You forgot to press the merge button.

**Comment by Hans5958** [comment]
Ladies and gentlemen, may I have your attention on this court order added hours ago?

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

**Comment by niteshraj2310** [comment]
no

**Review by seanpm2001 — COMMENTED** [review]
No

**Review by seanpm2001 — COMMENTED** [review]
No

**Review by seanpm2001 — COMMENTED** [review]
No

**Comment by seanpm2001** [comment]
Die in a fire RIAA

**Review by its-pablo — COMMENTED** [review]
no

**Comment by adi8900** [comment]
no

**Pull request closed without merging**
