### PR TITLE
Private Fork?

### PR DESCRIPTION
**Pull request by Kyusetzu**
Yeah, publish all the others and black one out :wesmart:

### CODE REVIEW

**Review by ankurpandeyvns — APPROVED** [review]

**Review by samuei — APPROVED** [review]

**Comment by MrMelon54** [comment]
why should any details in this document be private we deserve to know all the details of whoever wants rid of youtube-dl

**Review by MrMelon54 — APPROVED** [review]

**Comment by My1** [comment]
maybe because these forks were set as private repos? no idea.

**Review by shirt-dev — APPROVED** [review]

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

But to answer the specific question raised... GitHub will occasionally redact information from a notice with a `[private]` notation where it includes private personal information, references a private repository, or includes other private information that is not necessary to understanding the complaint. From GitHub's [DMCA Policy](https://docs.github.com/en/github/site-policy/dmca-takedown-policy#d-transparency):

>We post redacted copies of any legal notices we receive (including original notices, counter notices or retractions) at https://github.com/github/dmca. We will not publicly publish your personal contact information; we will remove personal information (except for usernames in URLs) before publishing notices.

In this case, the [link on line 24](https://github.com/github/dmca/pull/8173/files#diff-f16f7d179a7e091c18d785e249bbc76c585354e1286fe113b789c94c0c3b7791R24) had a typo in the notice we received. So it was not linking to a repository that was actually being accused. Rather than correct that typo in the published version—because we do not *alter* the content of the notices we publish—we decided to redact it instead. Sorry if this added any undue confusion. 

We understand that you may have other questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by MrMelon54** [comment]
Maybe something like `[private (due to incorrect address)]` would have been more suitable?

**Pull request closed without merging**
