### PR TITLE
Update 2016-05-08-Netronian.md

### PR DESCRIPTION
**Pull request by emiliano1**
Privacy concerns

### CODE REVIEW

**Comment by ohld** [comment]
LGTM

**Comment by vitalkanev** [comment]
[as I said here](https://github.com/github/dmca/pull/3887#issuecomment-412251655)

**Comment by emiliano1** [comment]
Thank you

**Comment by jessephus** [comment]
We do not regularly monitor this repository, and we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to it. 

I realize this response is almost certainly not useful anymore, but just in case you're still interested in contacting us, see our [Contributing Guidelines](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to see what your alternatives are.

**Pull request closed without merging**
