### PR TITLE
Added 2020/10/2020-10-23-RIAA.kek

### PR DESCRIPTION
**Pull request by george-bush-420**
The markdown screwed with how the lyrics were rendered. So I changed the extension from md to kek.

### CODE REVIEW

**Comment by altaway** [comment]
The markdown format screwed the way the lyrics were shown, so I changed the extension from md to kek.

**Review by MySixSenses — APPROVED** [review]
For Youtube-dl

**Review by NotchedDeveloper — APPROVED** [review]
For YTDL.. 🚀

**Comment by starikcetin** [comment]
Topkek

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
