### PR TITLE
Fix use typo (yse)

### PR DESCRIPTION
**Pull request by shawnlinxl**

### CODE REVIEW

**Comment by LeadroyaL** [comment]
Another typo is "mpw", it should be "now".

**Comment by tml104** [comment]
I am not English native speaker but I think that “clone” and “reupload” in third paragraph should be in the past tense. Is that right?

**Comment by CodeingBoy** [comment]
I think these notices should keep untouched . Also, Github only allows @hubot merging changes in, there's no personal PR were merged. (Search PR using `is:pr is:closed is:unmerged` to see the list)
Instead, I suggest providing corrected notice in committer's personal repository, which helps other people reading this notice.

**Comment by jessephus** [comment]
>I think these notices should keep untouched . Also, Github only allows @hubot merging changes in, there's no personal PR were merged.
☝️ 

https://github.com/github/dmca#contributing
>We do not accept Pull Requests in this repository. Feel free to comment or make suggestions, but note that we do not actively monitor contributions to this repository. If you would like to contact GitHub about this repository, please contact [GitHub Support](https://github.com/contact/). If you would like to submit a DMCA notice or counter notice, see our [DMCA Policy](https://help.github.com/articles/dmca-takedown-policy/#f-submitting-notices) pages for information on how to do so.

**Pull request closed without merging**
