### PR TITLE
DMCA counter notice

### PR DESCRIPTION
**Pull request by actsl**
DMCA counter notice against https://github.com/github/dmca/blob/master/2017/2017-06-23-Kiss.md

### CODE REVIEW

**Comment by ryantheleach** [comment]
It clearly says that they want the _project_ removed, not the repository. It never should affected your whole repo :(

**Comment by My1** [comment]
well, apparently it did, so he wrote this counter notice

**Comment by ryantheleach** [comment]
@My1 That's my entire point.

**Comment by My1** [comment]
but honestly I wonder why they killed off the whole repo, especially since the URL to the repo itself was never stated in the original notice, just the direct link to the file.

**Comment by jessephus** [comment]
Sorry for the delayed response. We do not regularly monitor this repository, and we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to it. 

If you'd like to submit a counter notice, please our [DMCA Counter Notice contact form](https://github.com/contact/dmca-counter-notice).

**Comment by actsl** [comment]
> If you'd like to submit a counter notice, please our DMCA Counter Notice contact form.

 

Yes, i certainly used that repeatedly, as well as sent the counter notice to copyright@github.com, until my counter notice was finally posted to the dmca repository at https://github.com/github/dmca/blob/master/2017/2017-07-14-Kiss-CounterNotice.md , but that was after i committed the referred counter notice.

 

Sincerely,

 

Tarvo

 

Sent: Tuesday, July 25, 2017 at 8:28 PM

**Comment by My1** [comment]
@jessephus then why does this repo even use pull requests? cant you guys disable those?

**Comment by jessephus** [comment]
No.

**Pull request closed without merging**
