### PR TITLE
Delete 2020-10-23-RIAA.md

### PR DESCRIPTION
**Pull request by desuex**

### CODE REVIEW

**Review by Parapass — APPROVED** [review]

**Review by Picoseconds — APPROVED** [review]

**Review by Bloxycube — APPROVED** [review]

**Review by MySixSenses — APPROVED** [review]
FOR Youtube-dl

**Review by unbeatable-101 — APPROVED** [review]

**Review by NeRdTheNed — APPROVED** [review]

**Review by sdomi — APPROVED** [review]

**Review by AlphaHot — APPROVED** [review]

**Review by williamd1k0 — APPROVED** [review]

**Review by andraantariksa — APPROVED** [review]

**Review by InsightGit — APPROVED** [review]

**Review by 0xbkt — APPROVED** [review]

**Review by RedL0tus — APPROVED** [review]

**Review by mon5termatt — APPROVED** [review]

**Review by Surendrajat — APPROVED** [review]

**Comment by fabianhjr** [comment]
Deleting the DMCA request is not the same as GitHub restoring the `youtube-dl` repositories.

I would suggest either adding an IPFS pointer to the last clone of the repository though. (Or an git-ssb link)

**Review by MightyPork — APPROVED** [review]

**Review by OriginCode — APPROVED** [review]
LGTM.

**Review by 12-Seconds — APPROVED** [review]

**Review by EdisonJwa — APPROVED** [review]
LGTRIAA

**Review by mo10 — APPROVED** [review]

**Review by Jackojc — APPROVED** [review]

**Review by Stang-wm — APPROVED** [review]

**Review by imachug — APPROVED** [review]

**Review by DominykasPetke — APPROVED** [review]

**Review by mininmobile — APPROVED** [review]
image

**Review by lululombard — APPROVED** [review]

**Review by L33Tech — APPROVED** [review]

**Review by canerozer — APPROVED** [review]

**Review by stanislavkozlovski — APPROVED** [review]

**Comment by vitalkanev** [comment]
**DO NOT** send pull requests to this repository. I'd recommend the developer to file a counter notice instead.

**Comment by fabianhjr** [comment]
> DO NOT send pull requests to this repository. I'd recommend the developer to file a counter notice instead.

Sure, if they want to send their real identities and addresses to the RIAA since they will clearly not file spurious claims with an army of lawyers.

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
