### PR TITLE
Added 2020/06/2020-06-23-kubezilla.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2020/06/2020-06-23-kubezilla.md

### CODE REVIEW

**Comment by collabnix** [comment]
I am ready to remove the image. Can you please help me in bringing back the site as we have BIG event coming up.

**Comment by collabnix** [comment]
I have raised a ticket with GitHub too.

**Comment by iomintz** [comment]
Contact GitHub through their DMCA email address if you haven't already. This isn't the venue.

**Comment by ajeetraina** [comment]
I raised a request with GitHub. Any idea how we can expedite this?

**Comment by collabnix** [comment]
May i know what is the email address to which I need to send to. Also, is there any way to expedite this.

**Pull request merged**
