### PR TITLE
i feel it didn't capture the seriousness of the situation, now fixed

### PR DESCRIPTION
**Pull request by lamados**
RIAA you can thank me later <3

### CODE REVIEW

**Review by oliver-ni — APPROVED** [review]
def looks great

**Comment by RandoNandoz** [comment]
LGTM!

**Review by RandoNandoz — APPROVED** [review]
Looks pretty good to me!

**Comment by 5kbl** [comment]
Yep, looks good! Great job!

**Review by ricardofachinello — APPROVED** [review]

**Review by Mhowser — APPROVED** [review]

**Review by technoabyss — APPROVED** [review]

**Review by BitesizedLion — APPROVED** [review]

**Review by MutedJam — APPROVED** [review]
Looking very serious to me. I approve.

**Review by emilweth — APPROVED** [review]
LGTM (* ^ ω ^)

**Review by btwiusegentoo — APPROVED** [review]
This is pretty good now

**Review by alexbunt — APPROVED** [review]
Perfect!

**Review by badstagram — APPROVED** [review]

**Review by SaiintBrisson — APPROVED** [review]

**Comment by jessephus** [comment]
Hi :wave: As much as we would love ❤️ to merge this one 1️⃣ , we are closing 📪 this pull request because we [do not ⛔ accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this ☝🏽 repository. Feel free 🆓 to keep the discussion 🗣️ going in this thread 🧵. Please just be mindful 🧠 to keep the discussion respectful 🙊 and consistent with [GitHub’s :octocat: Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We 👪 understand that you may have questions ❓ about this takedown 👇🏽. Although we do not normally monitor 💻 comments posted 📮 to this repository, our team 👥 is reading 📖 through the comments and questions❓ in this and other recent threads 🧵 to see 👁️ where we may be able to clarify 🔎 our policies or answer 🆘 some common questions. Thanks. 🙇🏽

**Pull request closed without merging**
