### PR TITLE
Added 2015-09-22-wahoo.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2015-09-22-wahoo.md

### CODE REVIEW

**Comment by jomo** [comment]
@bucaran doesn't `wahoo` use the MIT License? MIT allows…
> to deal in the Software without restriction, including **without limitation** the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so

**Comment by jomo** [comment]
So I had a little chat with @bucaran where I tried to prove my point but we weren't really getting anywhere.

There has been some previous discussion in https://github.com/wa/wahoo/issues/95 ([archive](https://archive.is/jsMXT)) and https://github.com/oh-my-fish/oh-my-fish/issues/56 ([archive](https://archive.is/lU35x)). However, according to @derekstavis and @bpinto the comments at the wahoo issue were manipulated by @bucaran :confused: 

Anyway, I wasn't involved in any of the previous discussion or contributions. I just wanted to point this out and feel sad about OMF being DMCA'd :cry:

**Comment by jomo** [comment]
Counter Notice was [filed here](https://github.com/github/dmca/pull/321) :+1:

**Comment by derekstavis** [comment]
I have some other proofs of issue thread manipulation:

issue 95-bpinto
issue 95-bpinto-email

Also [here](https://www.dropbox.com/s/z063rxq5njy6ay6/issue%2395.pdf?dl=0) I have a PDF scrape of https://github.com/wa/wahoo/issues/95

**Comment by derekstavis** [comment]
I have also e-mailed GitHub about our stolen repository, which now resides in https://github.com/fishline/fin. You can check that even with zero lines of code it haves lots of stars and I'm listed as a contributor:

derekstavis

**Comment by jomo** [comment]
I dislike how GitHub doesn't indicate when a comment was edited or deleted by someone (especially if not by the author). Would make this much more obvious.

**Comment by bucaran** [comment]
Nothing on that thread that I could have moderated justifies @bpinto actions and violating the MIT license by failing to attribute my copyright.

#### Folks looking for a discussion room:
### :point_right:   https://gitter.im/fishline/fin

#### Folks looking for more opinions →
<h3>:point_right:  <a href="https://news.ycombinator.com/item?id=10271304">news.ycombinator.com/item?id=10271304....</a></h3>

#### My version of the facts:

+ I worked in OMF for almost a year? I served as both owner and admin.
+ I rewrote most of OMF, but I didn't like how it was structured and decided to create a new, original system, e.g, Wahoo. 
+ Recently, Bruno and I talked, and decided to get rid of the old OMF and replace it with Wahoo.
+ We had disagreements over the direction of the project and ended out relationship. During the break up process, Bruno secretly moved the repo from fish-shell back to the omf org. I reacted quickly and dominated the repo before it was taken from me, disbanded it, and will use it to host a completely different, new project, _Fin_.
+ He created a new repo, which is the repo that was DMCA'd and pushed the old `git` history there, while they did fix a couple of bugs? they also modified the license and failed to attribute all of the work was under my "

**Pull request merged**
