### PR TITLE
RIAA's DMCA Takedown Request is invalid

### PR DESCRIPTION
**Pull request by cybrefox**

### CODE REVIEW

**Review by rbnkrnn — APPROVED** [review]

**Review by andrew77768 — APPROVED** [review]

**Review by ivanka2012 — APPROVED** [review]
Looks great to me

**Review by Terrobility — APPROVED** [review]

**Review by xfnw — APPROVED** [review]
i agree

**Comment by Europia79** [comment]
While I'm skeptical about the legitimacy of the take-down, I had to down-vote because you did not provide an argument for your position.

**Review by polarisfm — APPROVED** [review]

**Review by stephen304 — APPROVED** [review]

**Review by Margen67 — APPROVED** [review]

**Review by Bloxycube — APPROVED** [review]

**Review by Fusl — APPROVED** [review]

**Review by gluons — APPROVED** [review]

**Review by lululombard — APPROVED** [review]

**Comment by Chew** [comment]
> While I'm skeptical about the legitimacy of the take-down, I had to down-vote because you did not provide an argument for your position.

Here's your argument:

I've investigated this report and found it was in bad faith. The code itself did not break any laws. People abusing YouTube's faulty system is not at the fault of the people.

Why are you not taking down browsers, who are able to play videos just fine? Why are you not taking down screen recording software that's perfectly capable of just recording it? This is a targeted attack.

Fair use was not taken into account. Instead of pressuring YouTube to fix their system, you're playing a game of cat and mouse you'll never win.

I understand my words will fall silent here, and I will absolutely not fight to hold this position, but here is the argument you so desperately wanted.

**Review by L33Tech — APPROVED** [review]

**Review by bkhl — APPROVED** [review]

**Comment by 3n-k1** [comment]
@Europia79 by the logic of this takedown, literally all computers are illegal under the CFAA and DMCA because they could be used to do illegal things. since that's not how those acts work, the takedown is not only invalid, but an act of perjury. submitting a DMCA takedown requires a good-faith claim that the work is in violation of copyright *under penalty of perjury*. as the RIAA's notice was so blatantly invalid, it's perjury, which is a us federal felony

**Comment by Europia79** [comment]
> The code itself did not break any laws. 

Yeah, that was my initial thought, until I read the DMCA Anti-Circumvention policy, which gives them "a case" in the eyes of the court...  Altho, I think their foundation is extremely shaky, given that, in my opinion, such a work is not "primarily designed for the purpose of circumventing a technology measure", but rather, it's primary purpose is for the backup & preservation of important & significant works of our time, and the fact that it allows for the download of copy-righted works is (1) NOT relevant, and (2) falls on the responsibility of the user.

But yeah, when I first heard that a MUSIC company had filed a DMCA copy-right claim against some open source software, I raised my eye-brows & thought to myself: "WTF ?  How could they possibly have a claim on CODE ?" (someone else's code at that).

So, hopefully you can understand my outrage when investigating the issue, I come here, only to find some kid who has posted **RIAA's DMCA Takedown Request is invalid #8133** without providing an argument:  I'm thinking to myself:  "Well, yeah, probably, but no court is going to accept that".  And nor should I or anyone of you.  

Honestly, I had a much higher opinion & respect for coders and this has shattered my worldview of them.

Now, we live an age where a blank post is up-voted while asking for an argument is down-voted.  That's okay, I'll take it as a badge of honor.

> I understand my words will fall silent here

What do you mean ?  ...I was one the one who got 28 down-votes before someone bothered to reply with an argument:  It's obviously MY words that will fall on deaf ears here.

> @Europia79 by the logic of this takedown, literally all computers are illegal under the CFAA and DMCA because they could be used to do illegal things. since that's not how those acts work, the takedown is not only invalid, but an act of perjury. submitting a DMCA takedown requires a good-faith claim that the work is in violation of copyright under penalty of perjury. as the RIAA's notice was so blatantly invalid, it's perjury, which is a us federal felony

I agree.

**Comment by Project-Magenta** [comment]
Here's my attempt (I am not the OP):

<sub>Disclaimer: I am not a lawyer and I am not giving legal advice. The following text purely consists of my own assumptions made from trivial research.</sub>

> The clear purpose of this source code is to (i) circumvent the technological protection measures used by authorized streaming services such as YouTube, and (ii) reproduce and distribute music videos and sound recordings owned by our member companies without authorization for such use. We note that the source code is described on GitHub as “a command-line program to download videos from YouTube.com and a few more sites.”

## Addressing the point (i)

Citing 17 U.S.C. § 1201:
> a technological measure “effectively protects a right of a copyright owner under this title” if the measure, in the ordinary course of its operation, prevents, restricts, or otherwise limits the exercise of a right of a copyright owner under this title.

If videos can be placed under a license which makes ineffectual these rights, can such circumvention really be illegal under 1201?

## Addressing the point (ii)

The point (ii) can be found to be invalid from the documentation of the program. None of the RIAA's members own any videos mentioned as examples or suggested in the documentation. Their supposed "suggestion" is in a test case internally used by developers to test the project. This in no way asserts that downloading RIAA's members' videos is recommended, much less the "clear purpose" of the source code.
YouTube videos can be explicitly placed under a CC license that permits copying.

Instead of making a valid claim that they own the source code, the RIAA appears to be misusing GitHub's DMCA claim system to take down the `youtube-dl` sources without any court involvement.
The mentioned file is not a DMCA claim, and should not be taken as such and present in this repo.
Instead, the RIAA is asserting that the very source code is itself illegal.

**Comment by 3n-k1** [comment]
> Honestly, I had a much higher opinion & respect for coders and this has shattered my worldview of them.

someone disagreeing with an obviously false and illegal dmca takedown has shattered your worldview? that's a pretty fragile worldview you must have. that which is claimed without evidence can be dismissed without evidence

**Comment by Europia79** [comment]
So, you've just learned the news of this DMCA takedown request and you goto the primary source:  Here... only to find an empty post with NO information:  That's what @Picoseconds wants you to see.  Congrats kid:  **+1** Amazing contribution there /s.

Now I can see why the other kid said: "I understand my words will fall silent here".  Because he intuitively knows that kids now-a-days do not like to read, which is why they prefer the EMPTY POST to the ones with insightful info.

@Project-Magenta  @3n-k1 @Chew  Thanks for info, but I have to ask:  How does it feel knowing that an EMPTY POST will receive more likes & appreciation than yours ?  ...which I can definitely tell took more thought & time to produce.

**Comment by Project-Magenta** [comment]
I am Picoseconds also btw

**Comment by 3n-k1** [comment]
@Europia79 lol who cares
i don't spend my life worrying about getting likes on github lol

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines), and do not re-post content to this repository that was the subject of a takedown notice, or we may need to delete the pull request.

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by 3n-k1** [comment]
@jessephus i know you're probably not the person to ask, but since you're the only point of contact for github we've seen so far i'm gonna ask anyway: does github have a policy of enforcing *all* false dmca requests, or just ones from large corporations? because i have copyrighted content on youtube, and i guarantee if i had sent this exact same notice as a private citizen and not a giant media conglomerate, nothing would have happened

i also think it's really interesting that github acted incredibly swiftly on this (same day iirc?) but lets people straight up drop slurs and say racist things on the site without repercussion. y'all took longer to restore the retroarch repos than to rip down an entire repo and all its forks over an illegal, perjurous dmca claim

**Comment by Chew** [comment]
I'm not sure how their internal system worked, but when I filed a DMCA claim it took a good day or two to receive a response, asking for clarification how the license was violated (unfortunately it was not violated, so I had to drop it, curse you os licenses!!!). There's no way to tell when this was filed unfortunately.

The repo owners (in this case ytdl-org) have every right to file a counter claim (and win, because as proven this is on an unfair basis). 
GitHub, to protect themselves, *disabled* the repository, and obviously there is a much more looming threat of a lawsuit from a giant cooperation than a individual. 

If this a fight they want to fight, RIAA could take this to court if they really cared (but because of how finicky the whole situation is, I doubt they will, because they'd likely lose). If Google had DMCA'd this, it would be a whole different scenario, one that would easily be solved by removing only the YouTube extracting (or whatever Google services it can extract from), and changing the name, and Google would be fine with it at this point, but this is all hypothetical.

The RIAA has no right or basis as they own none of the content of the repo nor does what the repo's code does affect them, which I assume spurred this whole thing to begin with.

While I agree this is unjust, there's nothing we can do, it's up to ytdl-org to, and I fully support their decision and right to make any call they choose.

**Comment by jessephus** [comment]
Since this involves a pending legal matter, we are not able to provide you with details about this particular case right now. But as I said, we are reading your questions to see how we can improve our processes and/or clarify things. Sorry that's not the answer you wanted.

**Comment by Project-Magenta** [comment]
@3n-k1 This isn't a DMCA request. This is an assertation that youtube-dl is inherently illegal

**Comment by 3n-k1** [comment]
@Project-Magenta the letter is a dmca takedown notice. it states it explicitly in the letter: https://github.com/github/dmca/pull/8133/files#diff-f16f7d179a7e091c18d785e249bbc76c585354e1286fe113b789c94c0c3b7791L92

the entire letter is actually just a simple dmca template, i know because i've used the exact template several times. notice how here (https://github.com/github/dmca/pull/8133/files#diff-f16f7d179a7e091c18d785e249bbc76c585354e1286fe113b789c94c0c3b7791L10) they even straight up mention the "under penalty of perjury" quote required for a dmca takedown notice

**Pull request closed without merging**
