### PR TITLE
Delete 2020-10-23-RIAA.md

### PR DESCRIPTION
**Pull request by jam3st**
Seriously? No, seriously? No you cannot go after Alphuckbet so you go after the little guys? You have made some serious enemies Micro$oft.

If you are looking to file or dispute a takedown notice by posting to this repository, please STOP :stop_sign: because we do not accept Pull Requests or other contributions to this repository.

Read on to learn about the available paths forward.

Please note that re-posting the exact same content that was the subject of a takedown notice without following the proper process ([outlined below](#responding-to-a-dmca-notice)) is a violation of GitHub’s [DMCA Policy](https://docs.github.com/en/github/site-policy/dmca-takedown-policy) and [Terms of Service](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies). If you commit or post content to this repository that violates our Terms of Service, we will delete that content and may suspend access to your account as well.

#### Submitting a DMCA Notice

If you are a copyright owner wishing to submit a takedown notice, read our [DMCA Policy](https://docs.github.com/en/free-pro-team@latest/github/site-policy/dmca-takedown-policy) and [Guide to Submitting a DMCA Takedown Notice](https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-takedown-notice). You can submit the actual notice using our special [Copyright Claims Contact Form](https://github.com/contact/dmca).

#### Responding to a DMCA Notice

If you are the owner of a repository that has been taken down, you have two main options:

  - Do you want to [make changes](https://docs.github.com/en/free-pro-team@latest/github/site-policy/dmca-takedown-policy#c-what-if-i-inadvertently-missed-the-window-to-make-changes) to the repository that would remove the allegedly infringing content? If that is possible in your case, [contact us](https://support.github.com/contact) to let us know that you would like to make the changes.

  - Do you want to formally dispute the action by [submitting a counter notice](https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-counter-notice)? Maybe the person sending the takedown notice does not hold the copyright or did not realize that you have a license or made some other mistake in their takedown notice. If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by [submitting a counter notice](https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-counter-notice). If you do, we will wait 10-14 days and then re-enable your content unless the copyright owner initiates a legal action before then.

If you do not want to make changes or dispute the notice, but still have general concerns about the copyright laws and how they apply in your case, know that GitHub and developers have the opportunity and a voice to advocate for changes in law and public policy to better support software development. We are constantly looking to [advocate for developers](https://github.blog/category/company/policy/), so feel free to [reach out](https://support.github.com/contact) and let us know your concerns. We also encourage you to [learn more about copyright and speak up](https://docs.github.com/en/free-pro-team@latest/github/site-policy/dmca-takedown-policy#learn-more-and-speak-up) by reaching out to the Copyright Office or your local lawmakers to voice your concerns.

### CODE REVIEW

**Review by exorcist-git — APPROVED** [review]
Seems legit. Merge now!

**Comment by Testsr** [comment]
I propose that this pull request should be closed, because Github has already locked the repostory and deleting the file does not mean that the DMCA does not apply suddenly. Submit a counter notice instead.

**Comment by Testsr** [comment]
BTW, I have a question for Github. Has there been a counter notice, or lawsuit notification that GitHub can provide?

**Comment by exorcist-git** [comment]
i have a question for github too ... why dont they shove this dmca thing up their ass and leave people do what they want on the internet?

**Comment by Testsr** [comment]
Because GitHub does not want to sued for copyright infringement that will happen eventually. GitHub would be overwhelmed with lawsuit cases. DMCA is not optional for this kind of website.

**Comment by Aholicknight** [comment]
> i have a question for github too ... why dont they shove this dmca thing up their ass and leave people do what they want on the internet?

Because Github (Microsoft) does not want to be sued for leaving copyright infringement on their website. If they left it open, they could face fines or more.

**Comment by will-pace** [comment]
Hi :wave:  We are closing this pull request because we do not accept contributions to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with GitHub’s Community Guidelines.

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
