### PR TITLE
Create ascii smiley face

### PR DESCRIPTION
**Pull request by zetanor**
added smiley face

### CODE REVIEW

**Review by r3muxd — APPROVED** [review]

**Review by sloev — APPROVED** [review]
noseless smileys are under appreciated

**Review by PatheticMustan — APPROVED** [review]

**Comment by mutageneral** [comment]
> noseless smileys are under appreciated

yes they look so cute :)

**Review by fitojb — APPROVED** [review]
Wholesome =)

**Comment by H1ghBre4k3r** [comment]
Looks like it passed all of the integrations tests. I see no reason, not to accept it. :^)

**Review by H1ghBre4k3r — APPROVED** [review]

**Review by Askalein1234 — APPROVED** [review]

**Review by Firepal — APPROVED** [review]
Functional, yet stylish. Follows the global code rules.
Such a good change, would push into master!

**Comment by will-pace** [comment]
Hi 👋 We are closing this pull request because we do not accept contributions to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with GitHub’s Community Guidelines.

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by sloev** [comment]
btw i saw this on hackernews the other day:
https://github.com/github/dmca/commit/e672d697b36e82007f2f7c98747937895981e697

**Comment by zetanor** [comment]
:(

**Pull request closed without merging**
