### PR TITLE
Incorrect assessment

### PR DESCRIPTION
**Pull request by G2G2G2G**
I can assure you the 3 mentioned songs are terrible and not even worth stealing. So the fact is, nobody used youtube-dl for that.

### CODE REVIEW

**Review by sickcodes — APPROVED** [review]

**Review by Faith1sGay — APPROVED** [review]

**Comment by nerrixDE** [comment]
abooose

**Comment by VoltrexMaster** [comment]
True

**Comment by bgette** [comment]
viva ytbdl

**Comment by 0x5066** [comment]
By that logic, we should start to issue DMCA takedowns on browsers, they aren't that different from ytdl

**Comment by Hammersamatom** [comment]
By there explanation, that would mean that _any_ operating system or piece of software with the ability to stream information from YouTube would be in violation. Blanket far reaching bullshit. The German court overseeing this even disagreed with the end result we're seeing here.

**Comment by aero31aero** [comment]
(I hate to point this out but PRs to this repository are unmonitored and the repo owners have to approach GitHub via their ways of handling DMCA to get this take down overturned. Making PRs here is literally shouting into the void.)

**Comment by G2G2G2G** [comment]
@aero31aero sounds like a personal problem (for them) because we'll just make 500 repos to replace it

**Comment by koalp** [comment]
Github actions can be used to download youtube songs. I think that github should be taken down too. 

I suggest that the RIAA issue a DCMA request immediatly about it. As an artist, I would be very worried about github actions beeing abused to download my songs :scream:

**Comment by notviri** [comment]
nooo you can't download the same files that the browsers stream from the exact same endpoints for free noooo 😢🍼
guys let's dmca https://github.com/chromium/chromium next

**Comment by MarkMcCaskey** [comment]
Mildly interesting observation:

https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-takedown-notice

says
> Include the following statement: "I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law. **I have taken fair use into consideration.**"

Emphasis mine.

Notably this notice doesn't include the text "fair use" anywhere and it's conspicuously missing from where it should be:

>We have a good faith belief that this activity is not authorized by the copyright owner, its agent, or the law. We assert that the information in this notification is accurate, based upon the data available to us.

Seems they're going out of their way to not mention fair use. Maybe they didn't consider it 😆

**Comment by notviri** [comment]
> ... they're going out of their way to not mention fair use. maybe they didn't consider it

Seems to be a common theme with any YouTube related takedown.

**Comment by sickcodes** [comment]
https://github.com/github/dmca/pull/8127

**Review by Roki100 — APPROVED** [review]

**Review by notviri — APPROVED** [review]

**Review by r4rdsn — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Review by toloveru — APPROVED** [review]

**Comment by toloveru** [comment]
Just mirrored the repo to [git.ghnou.su/mir/youtube-dl](https://git.ghnou.su/mir/youtube-dl). It's ridiculous that 3 songs in a readme can cause a takedown of a whole project. Not to mention that media is completely separate from tooling. Torrent clients can be used to download movies, yet those aren't being taken down either. There are valid uses for either and it's the responsibility of the user what they do with the tools they have.

**Review by 2secslater — APPROVED** [review]

**Review by VoltrexMaster — APPROVED** [review]

**Review by DiegoFleitas — APPROVED** [review]

**Review by robbyoconnor — APPROVED** [review]

**Review by Techno-Disaster — APPROVED** [review]

**Review by JakubVanek — APPROVED** [review]

**Review by Zandario — APPROVED** [review]

**Review by urmum-69 — APPROVED** [review]

**Comment by sserdda-liamE** [comment]
> Notably this notice doesn't include the text "fair use" anywhere and it's conspicuously missing from where it should be:

This isn't a copyright claim, it's a protection circumvention one.  AFAIK there's no fair use defense to the public posting of means to circumvent protections of copyrighted content.

**Comment by G2G2G2G** [comment]
> nooo you can't download the same files that the browsers stream from the exact same endpoints for free noooo 
> guys let's dmca https://github.com/chromium/chromium next
@notviri how do I make a pull request and delete all of chromium's code with a DMCA? I can't figure it out

**Review by RektWithStyle — APPROVED** [review]

**Review by bparker06 — APPROVED** [review]

**Review by fofofofofofofofo — APPROVED** [review]
give us back ytdl you record industry scum

**Comment by notviri** [comment]
@fofofofofofofofo https://codeberg.org/polarisfm/youtube-dl

**Comment by ThatLonelyMozza** [comment]
Other repositories we should DMCA because it can download videos from **[YouTube](https://youtube.com)** that literally nobody listens to anymore:
**[chromium/chromium](https://github.com/chromium/chromium)**
**[mozilla-mobile/firefox-ios](https://github.com/mozilla-mobile/firefox-ios)** (and it's parent/child repos)
**[curl/curl](https://github.com/curl/curl)**
**[github/github](https://github.com/)** (Not a repo but there's actions that can be used to download unpopular music)
**And 2M+ others...**

**Comment by Hans5958** [comment]
Confession: I unironnicaly liked "I Love It"

**Comment by Zopolis4** [comment]
I have reason to believe that microphones/speakers could be used to record/play sound. As youtube has the exclusive copyright to sound, all microphones and speakers are illegal.

**Comment by ThatLonelyMozza** [comment]
> I have reason to believe that microphones/speakers could be used to record/play sound. As youtube has the exclusive copyright to sound, all microphones and speakers are illegal.

And I have reason to believe that computers, tablets, and phones could be used to access the sound, and should therefore be banned along with microphones and speakers.

**Comment by jbruchon** [comment]
> This isn't a copyright claim, it's a protection circumvention one. AFAIK there's no fair use defense to the public posting of means to circumvent protections of copyrighted content.

YouTube streams do not have anti-copying protection. The data transmitted to the client is unencrypted. The data is publicly available and accessible. Their claim is false. Analogies are always a little dicey for technical things, but I'll throw one out anyway: this is like someone presenting you with a list of items when you go to the door of their home, you asking for one of the items, and them giving it to you. When you use youtube-dl they call it circumventing a copyright protection mechanism, but when you use your browser to go to YouTube and do the exact same thing, it's somehow different? Except it isn't. Use the Network tab in the developer tools and you can pick up the stream URLs in the clear. It's no different.

**Review by rahilwazir — APPROVED** [review]

**Review by oofdere — APPROVED** [review]

**Comment by NO-ob** [comment]
ragepewpewhd

**Review by y21 — APPROVED** [review]

**Review by ondrej008 — APPROVED** [review]

**Review by andrew-ld — APPROVED** [review]

**Review by xfnw — APPROVED** [review]

**Review by KurtBestor — APPROVED** [review]

**Review by RektWithStyle — APPROVED** [review]

**Review by TheToto — APPROVED** [review]

**Review by 0x5066 — APPROVED** [review]

**Comment by CreepySkeleton** [comment]
If Shake it Off isn't a masterpiece, I don't know what is.

**Comment by oofdere** [comment]
> If Shake it Off isn't a masterpiece, I don't know what is.

[this](https://www.youtube.com/watch?v=L9HaNbsIfp0) is an actual masterpiece

**Comment by ThatLonelyMozza** [comment]
> > If Shake it Off isn't a masterpiece, I don't know what is.
> 
> [this](https://www.youtube.com/watch?v=L9HaNbsIfp0) is an actual masterpiece

Holy..

**Comment by BrendanTCC** [comment]
> > If Shake it Off isn't a masterpiece, I don't know what is.
> 
> [this](https://www.youtube.com/watch?v=L9HaNbsIfp0) is an actual masterpiece

missed opportunity for [this](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Review by database64128 — APPROVED** [review]

**Review by Seluj78 — APPROVED** [review]

**Review by jerbob — APPROVED** [review]

**Comment by BachoSeven** [comment]
> Mildly interesting observation:
> 
> https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-takedown-notice
> 
> says
> 
> > Include the following statement: "I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law. **I have taken fair use into consideration.**"
> 
> Emphasis mine.
> 
> Notably this notice doesn't include the text "fair use" anywhere and it's conspicuously missing from where it should be:
> 
> > We have a good faith belief that this activity is not authorized by the copyright owner, its agent, or the law. We assert that the information in this notification is accurate, based upon the data available to us.
> 
> Seems they're going out of their way to not mention fair use. Maybe they didn't consider it

I think this is a pretty fair point, considered they clearly did not include that required statement on purpose, and since that is basically the core of the issue with this DMCA request

**Comment by Zopolis4** [comment]
made another repo https://github.com/Zopolis4/youtub-dl

**Comment by oofdere** [comment]
> > > If Shake it Off isn't a masterpiece, I don't know what is.
> > 
> > 
> > [this](https://www.youtube.com/watch?v=L9HaNbsIfp0) is an actual masterpiece
> 
> missed opportunity for [this](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

can't believe I forgot about [that](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by Nefomemes** [comment]
> ragepewpewhd
> 

Sorry to bother, what's your avatar anyways?

**Comment by Nefomemes** [comment]
> ragepewpewhd
>

**Review by Nefomemes — APPROVED** [review]

**Review by ThatLonelyMozza — APPROVED** [review]

**Review by simonxciv — APPROVED** [review]

**Comment by jessephus** [comment]
Hi 👋🏽  We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Comment by 0x5066** [comment]
What a shame.

**Comment by Hans5958** [comment]
@jessephus Tell your people that have power to write a public statement about this takedown.

**Comment by Hans5958** [comment]
Ladies and gentlemen, may I have your attention on this court order added hours ago?

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

**Comment by 0x5066** [comment]
It mentions convert2mp3.net (RIP, best site ever), but there is no mention of yt-dl itself, however the correlation is very interesting.

**Comment by toloveru** [comment]
> Ladies and gentlemen, may I have your attention on this court order added hours ago?
> 
> https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

"are prohibited from:

a) circumventing effective technical measures for protecting the sound recording “Kreise (Acoustic Solo Version)” by the artist Johannes Oerding without the consent of the defendants, as  occurred  regarding the “youtube.com/watch?v=wuc4vyoX44” video via the convert2mp3.net service.

b) producing a software and/or owning such software for commercial purposes and/or providing a service using the convert2mp3.net website, which makes it possible to duplicate  audio files of the YouTube service,  the URL of which are protected from direct access using ciphering or a similar measure, such as with respect to the “youtube.com/watch?v=wuc4vyoX044” video"

Correction of absolutely horrible spacing is my own. The wording hasn't been modified. Anyway, no problem court and plaintiff, because youtube-dl isn't using convert2mp3's services - quite possibly it's the other way around. That's what you get when people with no idea about technical matters start screwing with said technical matters. Back off already RIAA, you've lost.

**Comment by toloveru** [comment]
@jessephus There has been this [post](https://twitter.com/t3rr4dice/status/1320660235363749888) on Twitter featuring a screenshot of the #youtube-dl channel on Freenode, where Nat Friedman joined and said that the youtube-dl repository could - and that he'd like for it to be reinstated. Has any further progress been made on this so far?

**Comment by G2G2G2G** [comment]
@jessephus Get lost, dweeb.

**Comment by Testsr** [comment]
> Ladies and gentlemen, may I have your attention on this court order added hours ago?
> 
> https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA-court-order.pdf

To prove that a case against similar behavior has been successful before.

**Comment by toloveru** [comment]
2 weeks have passed and we still don't have any progress other than Nat Friedman joining an IRC chat and saying that the repo could go back up, and some tweets from GitHub.. saying exactly the same. I understand that this process is complicated and will take time, but I don't think this time is available. Already news outlets like [Bleeping Computer](https://www.bleepingcomputer.com/news/software/github-threatens-to-ban-users-who-bypass-youtube-dl-takedown), [ITWire](https://itwire.com/your-it/apps/github-warns-users-to-avoid-uploading-copies-of-youtube-dl-script.html) and [XDA](https://www.xda-developers.com/github-warns-of-bans-for-users-still-distributing-youtube-dl) have written about how [this commit](https://github.com/github/dmca/commit/df637000b1e0064dec76f74247389bc643f29482) from @jessephus threatens users with account suspensions when found reuploading the youtube-dl source code. It is unclear to me whether this only applies to the (deviously clever IMO, but nonetheless not permitted) additions to the DMCA repository, or to forks on GitHub in general. It seems that the news outlets assume the latter, is this correct?

Either way this doesn't seem like GitHub unanimously thinks this takedown could just be undone, as the tweets seem to try to make us believe. What _actual_ actions for reinstatement have been taken so far?

**Comment by Ardakilic** [comment]
The repo is back :tada:

https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by Hans5958** [comment]
UPDATE: It's official, RIAA just got their L. youtube-dl is back, boys!

GitHub's statement:
- https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/
- https://twitter.com/GitHubPolicy/status/1328365918750003203
- https://twitter.com/natfriedman/status/1328365679473426432

youtube-dl's statement: ytdl-org/youtube-dl#27013

DMCA reversal letter:
- https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf
- https://github.com/github/dmca/commit/e00bfb544e93bfd3066fe1699171964dd2dc29e0

**Comment by G2G2G2G** [comment]
@jessephus watch your back

**Comment by Antonio9212** [comment]
https://github.com/github/dmca/pull/8124#issuecomment-715625409

**Pull request closed without merging**
