### PR TITLE
Added 2021/01/2021-01-20-mpa-reversal.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2021/01/2021-01-20-mpa-reversal.md

### CODE REVIEW

**Comment by osiris-plus** [comment]
Lmao MPAA are bunch of idiots with no brains.

**Comment by jesec** [comment]
👍 Good job.

It would set a terrible and extremely concerning precedent if MPA is allowed to take down an open source software which has nothing in code, documentation or tests that tie it to IP infringement. nyaa is a high quality BitTorrent tracker software. It can be used to host a variety of legal contents.

What's next for MPA? My advice: try to take down nginx and Apache. Presumptively they have been used to host many infringing contents given they power a large chunk of Internet.

**Comment by osiris-plus** [comment]
Take down x86-64 and Internet, it's used to pirate their trash hollywood movies.

**Comment by DiegoFleitas** [comment]
nice

**Pull request merged**
