### PR TITLE
Added 2020/11/2020-11-16-RIAA-reversal-effletter.pdf

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2020/11/2020-11-16-RIAA-reversal-effletter.pdf

### CODE REVIEW

**Comment by DiegoFleitas** [comment]
> Get owned RIAA

now this sparks pog ✨ ✨

**Comment by ShantanuNair** [comment]
Beautiful ❤️

**Review by rugk — COMMENTED** [review]
Not reviewable, one should not put binaries in git repositories… :stuck_out_tongue_winking_eye: 

That said, this is of course great news here! :tada: :smiley:

**Comment by DiegoFleitas** [comment]
> 
> 
> Not reviewable, one should not put binaries in git repositories… 😜
> 
> That said, this is of course great news here! 🎉 😃 Thanks EFF! ❤️

GitHub allows you to preview pdf files! https://github.com/github/dmca/blob/e00bfb544e93bfd3066fe1699171964dd2dc29e0/2020/11/2020-11-16-RIAA-reversal-effletter.pdf

**Comment by 3n-k1** [comment]
a haiku:
i'd just like to say
yo, get fucked riaa
your takedown was false

but really, good. the takedown was clearly illegal. now we need to ask github, what will you do when this happens in the future? you've made it clear that your platform is ripe for copyright abuse and illegal takedown notices, how are you going to make sure this doesn't happen again? not every foss dev is going to be able to get help from the eff

you just had the riaa perjure themselves to try and screw over one of your users. are you just gonna let anyone do that? or is it just big corporations that can break the law and hurt your users?

**Comment by rugk** [comment]
> GitHub allows you to preview pdf files! https://github.com/github/dmca/blob/e00bfb544e93bfd3066fe1699171964dd2dc29e0/2020/11/2020-11-16-RIAA-reversal-effletter.pdf

Hehe, yeah, but no diff/line comments etc. possible… :upside_down_face:

**Pull request merged**
