### PR TITLE
Run cancerify through 2020-10-23-RIAA

### PR DESCRIPTION
**Pull request by ivanka2012**
The 2020-10-23-RIAA.md document has a few styling issues here and there.

```
https://github.com/heraldofsolace/Cancerify for the tool
'use_emoji': True, 'max_emoji': 10, 'use_lenny': True, 'b-ify': True, 'oof-ify': True
```

### CODE REVIEW

**Review by mininmobile — APPROVED** [review]
image

**Review by skid9000 — APPROVED** [review]

**Review by DrumSlayers — APPROVED** [review]
Thoses changes are crucial for the claim to be approved.

**Review by Ayase-252 — APPROVED** [review]

**Review by qwertz19281 — APPROVED** [review]

**Review by NotchedDeveloper — APPROVED** [review]

**Review by DiegoFleitas — APPROVED** [review]
Looks good to me!

**Review by TCLNA — APPROVED** [review]

**Comment by outout14** [comment]
The pull request should be promptly merged.

**Review by d-shaun — APPROVED** [review]
> THEy acknowledge thE oof those ಠ_ಠworks oof are ಠ_ಠ( ͡⎚ ͜ʖ ͡⎚)( ͠° ͜ʖ °)( ͠° ͜ʖ °)( ͠° ͜ʖ °)( ͠° ͜ʖ °)(⌐■_■)

This is beautiful.

**Review by Nefomemes — APPROVED** [review]

**Review by dragonis41 — APPROVED** [review]
Looks good, need a little bit more cancer maybe ?

**Review by eneskeles — APPROVED** [review]
LGTM 🚀

**Review by samuei — APPROVED** [review]
MY EYES

**Review by starikcetin — APPROVED** [review]
Nice jo🅱 🅱rother

**Review by shirt-dev — APPROVED** [review]

**Comment by jessephus** [comment]
Hi :wave: We are closing this pull request because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

**Pull request closed without merging**
