### PR TITLE
Added 2020/10/2020-10-23-RIAA.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2020/10/2020-10-23-RIAA.md

### CODE REVIEW

**Comment by shirt-dev** [comment]
bullshit takedown

**Comment by ftruzzi** [comment]
lol, when will RIAA and similar orgs realize how full of shit they are?

This will only lead to youtube-dl gaining even more users and the RIAA even more hatred. Also when you tell hackers they can't do things, they tend to find a way around it.

**Comment by Faith1sGay** [comment]
RIIIIIIPPPPPPPPPPPPP

**Comment by resynth1943** [comment]
What the fuck

**Comment by resynth1943** [comment]
@dstftw @phihag @remitamine @jaimeMF @yan12125 @rg3
Pinging youtube-dl contributors in the hope of notifying a collaborator 👍🏼

**Comment by phihag** [comment]
@BenLubar The URLs were test cases in `youtube.py`.

As a former maintainer of youtube-dl, I sincerely hope that somebody rescues the project, removing the offending code – it's a very small part of the whole project after all, not worth the trouble. I use youtube-dl to download lectures and view them on a train and without the overhead of a browser.

Since I've focused my work on other repositories, and as I am in a legal battle about my involvement with youtube-dl (despite any maintaining and work on the code ending years ago), I'm sad it can't be me.

**Comment by shirt-dev** [comment]
https://codeberg.org/shirt/youtube-dl

**Comment by newaccountnewlife** [comment]
https://git.disroot.org/41373770180505887198640312520077/yt-dl-clone

**Comment by newaccountnewlife** [comment]
> So is the RIAA claiming to own the copyright for youtube-dl, or are they claiming that a tool's existence is evidence of it being abused for a crime?
the latter

**Comment by VideoGameSmash12** [comment]
I've seen leeches with more intelligence than the Recording Industry Assholes of America.

**Comment by BenLubar** [comment]
> > They are claiming to legally represent Google, or at least YouTube.
> 
> Are you certain about this? I would assume that the copyright holder of music which was pirated due to circumvention of protection measures would have the ability to sue over said circumventions, not just the platform whose measures were circumvented.

They're not claiming any piracy occurred, only that the software *could* facilitate it (which is blatantly false - youtube-dl cannot download videos with DRM)

**Comment by ESWZY** [comment]
BACKUP YOUR CODE AT ONCE!

**Comment by tan-wei** [comment]
What a foolish decision!

**Comment by Sven65** [comment]
Hey, RIAA. Literally nobody likes you. Not even the artists you represent.

Go fuck yourselves, and for the good of society, stop existing.

**Comment by mohibo** [comment]
riaa can go fuck themselves

**Comment by beauxq** [comment]
This is not a DMCA request. It is not claiming ownership of any intellectual property in the repositories.
It doesn't belong in a "dmca" repository.

**Comment by 0anakreon0** [comment]
Working mirror: [https://gitlab.com/aab54/youtube-dl](https://gitlab.com/aab54/youtube-dl)
[https://bitbucket.org/aab54/ytdl](https://bitbucket.org/aab54/ytdl)

**Comment by iomintz** [comment]
> (which is blatantly false - youtube-dl cannot download videos with DRM)

if you mean movies and pay per view content on YouTube, that's true, but arguably all content on YouTube has DRM whether it uses Encrypted Media Extensions or not.

**Comment by confiq** [comment]
With shit like this, I have a feeling that Stallman was right!  

Any Github official response about this?

**Comment by stevefan1999-personal** [comment]
This is a public domain work, so this is widely distributed everywhere. 

And your malicious claim here is not going to work either, RIAA, smh. The only thing you did is just intervene the development but you have just never killed it totally and it will keep haunting you.

**Comment by Sven65** [comment]
This issue still isn't resolved, where's the responses?

**Comment by mentalisttraceur** [comment]
Sue the RIAA and all such entities for damages when they try to pull stuff like this.

Are you a user of youtube-dl who had legitimate use-cases interrupted?

Were you trying to learn something when this code became unavailable?

Are you an org that had to rack up ridiculous legal bills just to deal with this clearly bad faith and harmful action?

If you are an individual gainfully employed or could be, multiply the amount of time they wasted by making youtube-dl unavailable. Add in the productivity lost due to frustration and the like. Multiply that by your hourly rate.

There's literally a huge class here for a class action.

The RIAA is a sociopathic entity - regardless of how individually non-sociopathic the humans comprising it are. It does not care about how it effects most people. It has spent decades under selective pressures to only care about pleasing sociopathically profit-driven entities. It will never care about human experiences or ethics or societal good ...*unless* we inflict material costs on it until it must learns to at least act like it cares to not die.

**Comment by thecutefinder** [comment]
@mentalisttraceur I agree, and I'm glad that I'm not the only one who hasn't forgotten about this in 2023.

Abuse of the DMCA happens constantly, every day. It's too easy to abuse it. Nobody is EVER prosecuted for blatantly committing perjury in these takedown notices, and the only way to appeal them is to deanonymize yourself and let the lawyers know what your email and phone number are, what your name is, and where you live. And don't tell me that this information is not shown to the company that submitted the takedown. Claiming that completely forgets that DMCA subpoenas exist. It also acts like we should trust massive, for-profit, closed-source monopolies with information about who we are and where we live just because someone was unfortunate enough to be targeted by the broken copyright system.

It's not just youtube-dl that's been subject to this. A significant amount (if not the majority) of the notices in this repository are bullshit. Fair use only applies if you can hire an attorney. And if they're not bullshit in a legal sense, they're often over stuff that isn't immoral but violates the letter of the law. Face it.

Let's look at the Internet Archive. A non-profit is going to have to spend thousands (if not millions) of dollars going through the courts to fend off a massive corporation trying to destroy the freedom of the Internet.

Copyright is broken, and legislators don't want to fix it.

https://www.endcreativemonopolies.com/

**Review by AKayy2020 — COMMENTED** [review]
[c]()

**Pull request merged**
