### PR TITLE
Added 2020/11/2020-11-16-RIAA-reversal.md

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2020/11/2020-11-16-RIAA-reversal.md

### CODE REVIEW

**Comment by DiegoFleitas** [comment]
WE DID IT BOYS 💯 🎉 🎉

**Comment by BenLubar** [comment]
Is there any penalty for submitting a fraudulent DMCA request?

**Comment by endearingyoungcharms** [comment]
> Is there any penalty for submitting a fraudulent DMCA request?

At this rate, I think that we just should be happy that we have youtube-dl back.

**Comment by CreamyCookie** [comment]
@endearingyoungcharms We have reason to be happy, yes, but making sure this doesn't happen to other, maybe less popular projects, is important too.

The whole DMCA "guilty until proven innocent" / ban-first-ask-later approach is highly questionable. But given that it's here to stay (for now), there has to be a penalty for each fraudulent DMCA request.

**Pull request merged**
