### PR TITLE
Added 2020/10/2020-10-23-RIAA-court-order.pdf

### PR DESCRIPTION
**Pull request by hubot**
### Added files: 

* 2020/10/2020-10-23-RIAA-court-order.pdf

### CODE REVIEW

**Comment by Sven65** [comment]
BOOO, fuck the RIAA.

**Comment by novasharper** [comment]
This is from an old case. It's the result that was referenced in their DCMA request. Notice that the date is from 2017.

**Comment by Sven65** [comment]
Ah, my bad.

But still, fuck the RIAA.

**Comment by mohe2015** [comment]
I think that this doesn't actually apply to youtube-dl as it is AFAIK allowed to download copyrighted content for private use in Germany. convert2mp3net would probably not be considered private but youtube-dl is. Anyways somebody will develop an add-on to screen-record or whatever the video directly for sure to annoy them.

**Pull request merged**
