### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### Other Corrected URLs 
Was | Now 
--- | --- 
http://help.github.com/dmca-takedown/ | https://help.github.com/dmca-takedown/ 
https://developers.google.com/storage/docs/dmca | https://cloud.google.com/storage/docs/dmca 
https://www.chillingeffects.org/topics/1 | https://lumendatabase.org/topics/1

### CODE REVIEW

**Comment by jomo** [comment]
Hmm @jessephus  I don't understand why you don't accept PRs on this repo.
Of course sending DMCAs should go a different way but this one (and a few others) do make sense. Why are they always closed without a comment? I don't understand that :confused:

**Comment by jessephus** [comment]
>. . . this one (and a few others) do make sense . . .

I agree with the *content* of this one. But it is a violation of our Terms to open PRs or Issues via automated script, even though they may be well meaning, like this one. 

I cannot recall any others that I've seen that make sense. The only other PRs I remember seeing in recent history have been mistaken attempts to submit a formal DMCA notice, or they are satire/commentary, which people can be free to comment on and discuss, but we obviously aren't going to merge.

**Comment by jessephus** [comment]
c94f3c0

**Comment by jomo** [comment]
:+1:

**Comment by ReadmeCritic** [comment]
Thanks @jessephus

**Pull request closed without merging**
