### PR TITLE
I fixed it more for you. <3

### PR DESCRIPTION
**Pull request by hack-everything**

### CODE REVIEW

**Comment by prochac** [comment]
legit to me

**Comment by mininmobile** [comment]
image

**Review by mininmobile — APPROVED** [review]

**Review by lululombard — APPROVED** [review]

**Review by aUniqueUser — APPROVED** [review]

**Review by smartclash — APPROVED** [review]

**Review by moom0o — APPROVED** [review]

**Comment by rubikscraft** [comment]
Ish very nice

**Review by williamd1k0 — APPROVED** [review]

**Review by visika — APPROVED** [review]

**Review by ThePotato97 — APPROVED** [review]
Lgtm

**Comment by Nefomemes** [comment]
GitHub - Social Media for Programmers

**Review by NotchedDeveloper — CHANGES_REQUESTED** [review]
The gender reference on line 5 should obviously be formatted via accordance of PR #8129

**Comment by rysiekpl** [comment]
Can someone please tag this with #Hacktoberfest?

**Review by TheRandomMelon — COMMENTED** [review]
why are there 10,000 commits???

**Comment by jessephus** [comment]
Hi 👋🏽  We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

P.S. - No... this pull request does not qualify for Hacktoberfest. 😂 Nice try, though.

**Pull request closed without merging**
