### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dvtate**
#hactoberfest

### CODE REVIEW

**Comment by Zeryther** [comment]
This repository is an archive, notices should not be modified.

> We do not accept Pull Requests in this repository. Feel free to comment or make suggestions, but note that we do not actively monitor contributions to this repository. If you would like to contact GitHub about this repository, please contact GitHub Support. If you would like to submit a DMCA notice or counter notice, see our DMCA Policy pages for information on how to do so.

**Comment by HawaiinPizza** [comment]
> This repository is an archive, notices should not be modified.
> 
> > We do not accept Pull Requests in this repository. Feel free to comment or make suggestions, but note that we do not actively monitor contributions to this repository. If you would like to contact GitHub about this repository, please contact GitHub Support. If you would like to submit a DMCA notice or counter notice, see our DMCA Policy pages for information on how to do so.

This dude straight up delete the DMCA in the commit

**Comment by qorg11** [comment]
wtf? based soydev?

**Comment by ctjlewis** [comment]
lgtm

**Review by gluons — APPROVED** [review]

**Review by lululombard — APPROVED** [review]

**Comment by jessephus** [comment]
Hi 👋🏽  We are closing this pull request, because we [do not accept contributions](https://github.com/github/dmca/blob/master/CONTRIBUTING.md) to this repository. Feel free to keep the discussion going in this thread. Please just be mindful to keep the discussion respectful and consistent with [GitHub’s Community Guidelines](https://docs.github.com/github/site-policy/github-community-guidelines).

We understand that you may have questions about this takedown. Although we do not normally monitor comments posted to this repository, our team is reading through the comments and questions in this and other recent threads to see where we may be able to clarify our policies or answer some common questions. Thanks.

P.S. - No... this pull request does not qualify for Hacktoberfest. 😂 Nice try, though.

**Pull request closed without merging**
